- plugins/org.jboss.tools.openshift.client/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.common.core/src/org/jboss/tools/openshift/common/core/utils/StringUtils.java
- plugins/org.jboss.tools.openshift.ui/plugin.xml
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/explorer/OpenShiftExplorerLabelProvider.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/common/core/util/StringUtilsTest.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/explorer/OpenShiftExplorerLabelProviderTest.java
@adietish this should be the right pull
> [JBIDE-19180] Add styled labeling for resources to v3 OpenShift Explorer

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/explorer/OpenShiftExplorerLabelProvider.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/explorer/OpenShiftExplorerLabelProviderTest.java
@adietish Updated styling to be along the lines of what we discussed
> [JBIDE-19191] Improve styled text for openshift explorer

- features/org.jboss.tools.openshift.feature/.project
- features/org.jboss.tools.openshift.feature/build.properties
- features/org.jboss.tools.openshift.feature/feature.properties
- features/org.jboss.tools.openshift.feature/feature.xml
- features/org.jboss.tools.openshift.feature/license.html
- features/org.jboss.tools.openshift.feature/pom.xml
- features/org.jboss.tools.openshift.test.feature/.project
- features/org.jboss.tools.openshift.test.feature/build.properties
- features/org.jboss.tools.openshift.test.feature/feature.properties
- features/org.jboss.tools.openshift.test.feature/feature.xml
- features/org.jboss.tools.openshift.test.feature/license.html
- features/org.jboss.tools.openshift.test.feature/pom.xml
- features/pom.xml
- tests/pom.xml
@adietish I am unable to get the 'test' features to build as they cant find the actual test projects. Not certain what im missing locally
> [JBIDE-19162] Add feature projects to support new openshift v3 plugins

- plugins/org.jboss.tools.openshift.express.core/src/org/jboss/tools/openshift/express/core/ExpressCoreUIIntegration.java
- plugins/org.jboss.tools.openshift.express.core/src/org/jboss/tools/openshift/express/core/IConsoleUtility.java
- plugins/org.jboss.tools.openshift.express.core/src/org/jboss/tools/openshift/express/core/ICredentialsPrompter.java
- plugins/org.jboss.tools.openshift.express.core/src/org/jboss/tools/openshift/express/core/IEGitUI.java
- plugins/org.jboss.tools.openshift.express.core/src/org/jboss/tools/openshift/express/core/IQuestionHandler.java
- plugins/org.jboss.tools.openshift.express.core/src/org/jboss/tools/openshift/express/core/util/ExpressConnectionUtils.java
- plugins/org.jboss.tools.openshift.express.core/src/org/jboss/tools/openshift/express/internal/core/ExpressCoreActivator.java
- plugins/org.jboss.tools.openshift.express.core/src/org/jboss/tools/openshift/express/internal/core/connection/ExpressConnection.java
- plugins/org.jboss.tools.openshift.express.core/src/org/jboss/tools/openshift/express/internal/core/preferences/ExpressCorePreferences.java
- plugins/org.jboss.tools.openshift.express.core/src/org/jboss/tools/openshift/express/internal/core/preferences/IExpressCoreConstants.java
- plugins/org.jboss.tools.openshift.express.core/src/org/jboss/tools/openshift/express/internal/core/server/OpenShiftServerPublishMethod.java
- plugins/org.jboss.tools.openshift.express.ui/src/org/jboss/tools/openshift/express/internal/ui/ExpressUIActivator.java
- plugins/org.jboss.tools.openshift.express.ui/src/org/jboss/tools/openshift/express/internal/ui/console/TailFilesWizardPageModel.java
- plugins/org.jboss.tools.openshift.express.ui/src/org/jboss/tools/openshift/express/internal/ui/preferences/OpenShiftPreferencePage.java
- plugins/org.jboss.tools.openshift.express.ui/src/org/jboss/tools/openshift/express/internal/ui/wizard/application/ApplicationTemplateDetailViews.java
- plugins/org.jboss.tools.openshift.express.ui/src/org/jboss/tools/openshift/express/internal/ui/wizard/application/OpenShiftApplicationWizard.java
- plugins/org.jboss.tools.openshift.express.ui/src/org/jboss/tools/openshift/express/internal/ui/wizard/snapshot/RestoreSnapshotWizardModel.java
- plugins/org.jboss.tools.openshift.express.ui/src/org/jboss/tools/openshift/express/internal/ui/wizard/snapshot/SaveSnapshotWizardModel.java
@adietish fixed connection loading for v2 and renamed certain classes to follow conventions
> [JBIDE-19257] Fix loading v2 connection info from preferences

- plugins/org.jboss.tools.openshift.express.core/src/org/jboss/tools/openshift/express/core/ICredentialsPrompter.java
- plugins/org.jboss.tools.openshift.express.core/src/org/jboss/tools/openshift/express/internal/core/ExpressCoreActivator.java
- plugins/org.jboss.tools.openshift.express.core/src/org/jboss/tools/openshift/express/internal/core/LazyCredentialsPrompter.java
- plugins/org.jboss.tools.openshift.express.ui/src/org/jboss/tools/openshift/express/internal/ui/wizard/connection/CredentialsPrompter.java
- tests/org.jboss.tools.openshift.express.test/src/org/jboss/tools/openshift/express/test/AllTestsSuite.java
- tests/org.jboss.tools.openshift.express.test/src/org/jboss/tools/openshift/express/test/core/LazyCredentialsPrompterTest.java
@adietish fix connection prompt with lazy loader
> [JBIDE-19261] Fix v2 prompting for credentials when not connected

- plugins/org.jboss.tools.openshift.common.ui/plugin.xml
- plugins/org.jboss.tools.openshift.ui/plugin.xml
@adietish fix the refresh handler
> [JBIDE-19334] Fix registration of OpenShift v3 refresh handler

- plugins/org.jboss.tools.openshift.client/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/connection/Connection.java
> [JBIDE-19575] Update to support deprecation of com.openshift.client

- plugins/org.jboss.tools.openshift.ui/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/property/BuildConfigPropertySource.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/property/build/ImageChangePropertySource.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/property/build/WebHooksPropertySource.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/AllTestsSuite.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/property/build/BuildConfigPropertySourceTest.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/property/build/WebhooksPropertySourceTest.java
@adietish Adding buildconfig webhook.  Please review and merge
> [JBIDE-19007] add buildconfig webhook

- plugins/org.jboss.tools.openshift.common.core/META-INF/connectionsFactory.xml
- plugins/org.jboss.tools.openshift.core/META-INF/connectionFactory.xml
- plugins/org.jboss.tools.openshift.express.core/META-INF/connectionFactory.xml
https://issues.jboss.org/browse/JBIDE-19627
OpenShift features disable workspace selection
> JBIDE-19627 - OpenShift features disable workspace selection

- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/wizard/KeyValueWizardModel.java
- plugins/org.jboss.tools.openshift.ui/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/validator/LabelKeyValidator.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/validator/LabelValueValidator.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/application/ResourceLabelsPage.java
- tests/org.jboss.tools.openshift.test/META-INF/MANIFEST.MF
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/AllTestsSuite.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/validator/LabelKeyValidatorTest.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/validator/LabelValueValidatorTest.java
@adietish label validation for create from template
> [JBIDE-19476] Add label validation to create from template

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/connection/Connection.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/connection/ConnectionNotFoundException.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/connection/ConnectionsRegistryUtil.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/handler/NewApplicationHandler.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/application/ITemplateListPageModel.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/application/NewApplicationWizardModel.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/application/TemplateListPage.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/application/NewApplicationWizardModelTest.java
@adietish upload template from disk
> [JBIDE-19815] Upload template from local disk to create app

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/connection/OAuthDetailView.java
> [JBIDE-19895] Add explicit browser timeout to Oauth browser

- plugins/org.jboss.tools.openshift.express.ui/src/org/jboss/tools/openshift/express/internal/ui/wizard/application/ApplicationTemplateWizardPage.java
https://issues.jboss.org/browse/JBIDE-19853
GTK3 (only): Erroneous labels in application wizard tree
> JBIDE-19853 - GTK3 (only): Erroneous labels in application wizard tree

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/job/CreateApplicationFromTemplateJob.java
> [JBIDE-19937] Display reason why new app wizard fails for unsupported capability

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/connection/Connection.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/property/BuildConfigPropertySource.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/application/ResourceDetailsContentProvider.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/application/TemplateParameterColumnLabelProvider.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/application/TemplateParametersPage.java
- pom.xml
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/application/TemplateParameterColumnLabelProviderTest.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/property/build/BuildConfigPropertySourceTest.java
@adietish is this what you wanted for a PR for beta1?
> [JBIDE-20015] Fix retrieving webhook for source build strategy

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/connection/Connection.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/dialog/ResourceSummaryLabelProvider.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/explorer/OpenShiftExplorerContentProvider.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/explorer/OpenShiftExplorerLabelProvider.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/explorer/ResourceGrouping.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/handler/OpenInWebBrowserHandler.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/job/CreateApplicationFromTemplateJob.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/property/BuildConfigPropertySource.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/property/OpenShiftPropertySourceAdapterFactory.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/property/build/WebHooksPropertySource.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/application/BuildConfigWizardPage.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/application/ResourceDetailsContentProvider.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/application/TemplateListPage.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/core/connection/ConnectionTest.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/application/NewApplicationWizardModelTest.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/explorer/OpenShiftExplorerContentProviderTest.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/explorer/OpenShiftExplorerLabelProviderTest.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/job/CreateApplicationFromTemplateJobTest.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/property/build/BuildConfigPropertySourceTest.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/property/build/WebhooksPropertySourceTest.java
@adietish Please review and merge
> [JBIDE-20076] Replace enums to coincide with changes from OSJC-140

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/connection/Connection.java
- plugins/org.jboss.tools.openshift.ui/plugin.xml
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/explorer/OpenShiftExplorerContentProvider.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/handler/RefreshResourceHandler.java
@adietish Allow refresh of projects or any other resource
> [JBIDE-20050] Refresh resources

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/connection/Connection.java
> [JBIDE-20054] Update connection to copy rememberToken

- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/connection/ConnectionWizardPage.java
- plugins/org.jboss.tools.openshift.express.ui/src/org/jboss/tools/openshift/express/internal/ui/command/OpenInWebBrowserHandler.java
- plugins/org.jboss.tools.openshift.express.ui/src/org/jboss/tools/openshift/express/internal/ui/wizard/application/ApplicationTemplateDetailViews.java
- plugins/org.jboss.tools.openshift.express.ui/src/org/jboss/tools/openshift/express/internal/ui/wizard/domain/EditDomainWizardPage.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/handler/OpenInWebBrowserHandler.java
> [JBIDE-20311] corrected method calls to BrowserUtility

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/newapp/NewApplicationWizard.java
> [JBIDE-20370] Display the OpenShift Explorer when the 'New Application' wizard completes

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/portforwading/PortForwardingWizardModel.java
> [JBIDE-20404] Fix unable to show port forwarding wizard after previously stopping forwarding

- plugins/org.jboss.tools.openshift.common.core/src/org/jboss/tools/openshift/common/core/connection/IConnectionFactory.java
- plugins/org.jboss.tools.openshift.common.core/src/org/jboss/tools/openshift/common/core/utils/StringUtils.java
- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/connection/ConnectionWizardPage.java
- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/connection/ConnectionWizardPageModel.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/connection/ConnectionFactory.java
- plugins/org.jboss.tools.openshift.express.core/src/org/jboss/tools/openshift/express/internal/core/connection/ExpressConnectionFactory.java
> [JBIDE-20001] show signup link only if v2 default host selected

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/portforwading/PortForwardingWizardModel.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/portforwading/PortForwardingWizardPage.java
> [JBIDE-20349] Disable start and find ports when pod exposes no ports

- plugins/org.jboss.tools.openshift.ui/plugin.xml
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/handler/OpenInWebBrowserHandler.java
> [JBIDE-20022] Add  menu 'Show in Browser' menu for Connections

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/preferences/OpenShiftPreferencePage.java
JBIDE-20355 is ok through having the same validation code performed on FieldEditorPreferencePage#propertyChange method.
JBIDE-20371 is just initial since the Link content and behaviour needs to be implemented by someone with more knowledge about SWT and Eclipse API.
> JBIDE-20355 and JBIDE-20371

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/handler/AbstractOpenShiftCliHandler.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/preferences/OpenShiftPreferencePage.java
> [JBIDE-20354] add link to OS3 preferences when missing oc binary

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/connection/ConnectionEditor.java
> [JBIDE-20053] reset all views when using a new connection

- plugins/org.jboss.tools.openshift.common.core/src/org/jboss/tools/openshift/common/core/utils/StringUtils.java
- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/connection/ConnectionWizardPage.java
- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/connection/ConnectionWizardPageModel.java
- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/databinding/TrimTrailingSlashConverter.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/common/core/util/StringUtilsTest.java
> [JBIDE-20458] remove trailing slashes from server url

- plugins/org.jboss.tools.openshift.ui/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/dialog/ResourceSummaryDialog.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/webhooks/WebHooksComponent.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/webhooks/WebHooksDialog.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/webhooks/WebhookUtil.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/newapp/NewApplicationSummaryDialog.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/webhooks/WebhookUtilTest.java
> [JBIDE-20505] display webhooks after application has been created

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/OpenShiftCoreActivator.java
- plugins/org.jboss.tools.openshift.express.core/src/org/jboss/tools/openshift/express/internal/core/ExpressCoreActivator.java
> [JBIDE-20503] save connection preferences more often

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/newapp/TemplateListPage.java
> [JBIDE-20515] open template details on dbl-click

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/importapp/ImportApplicationWizard.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/newapp/NewApplicationWizard.java
> [JBIDE-19949] Automatically import sources once an application is created

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/newapp/ITemplateListPageModel.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/newapp/NewApplicationWizardModel.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/newapp/TemplateListPage.java
> [JBIDE-20477] Only display templates from selected project

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/connection/OAuthDetailView.java
> [JBIDE-20596] New App next wizard button should be enabled after entering token

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/job/DeployImageJob.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/common/EnvironmentVariable.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/DeployImageWizardModel.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/DeploymentConfigPage.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/IDeployImageParameters.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/IDeploymentConfigPageModel.java
This pull request:
* Allows users to add/edit/remove env vars during the deploy image workflow
* Modifies the DC stubbing to only add env vars that are new or changed
> [JBIDE-20542] Add env vars when deploying image

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/DeployImagePage.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/DeployImageWizardModel.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/IServiceAndRoutingPageModel.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/ServicePortAdapter.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/ServicePortDialog.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/ServicesAndRoutingPage.java
PR provides:
* Expose additional and/or edit ports
* Format fixes
> [JBIDE-20531] Add ports during deploy image work flow

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/validator/ProjectNameValidator.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/project/NewProjectWizardModel.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/project/NewProjectWizardPage.java
> JBIDE-20715 : add validation against duplicate project names

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/util/ResourceUtils.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/application/TemplateFilterTest.java
> [JBIDE-20946] add multi-tag filtering support for templates

- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/databinding/TabFolderSelectionProperty.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/newapp/TemplateListPage.java
> [JBDS-3489] : 1st iteration => use tabs for template selection

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/validator/DockerImageValidator.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/DeployImagePage.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/validator/DockerImageValidatorTest.java
> [JBIDE-21133] implement better docker image name validation

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/ServerSettingsViewModel.java
> [JBIDE-21329] reset source path when changing deployed project

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/ServerSettingsViewModel.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/ServerSettingsWizardFragment.java
> [JBIDE-21334] don't overwrite user's deploy path

- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/utils/OpenShiftUIUtils.java
- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/utils/UIUtils.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/ServerSettingsWizardFragment.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/DeployImageWizard.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/newapp/NewApplicationWizard.java
We now preselect the (1st) project that's selected in (using this order of prescedence)
* package explorer
* project explorer
* resource navigator
> [JBIDE-21352] server adapter wiz: preselecting project select in project views

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/property/OpenShiftResourceDocumentProvider.java
> [JBIDE-21399] keep the editor dirty if resource save/update failed

- plugins/org.jboss.tools.openshift.client/.classpath
- plugins/org.jboss.tools.openshift.client/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.client/build.properties
- plugins/org.jboss.tools.openshift.client/pom.xml
@fbricon @adietish To handle breaking api changes in the rest client
> bump client plugin to 4.0.0-SNAPSHOT for api changes

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/connection/ConnectionProperties.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/WatchManager.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/explorer/OpenShiftExplorerContentProvider.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/handler/RefreshResourceHandler.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/models/DeploymentResourceMapper.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/models/IProjectAdapter.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/models/OpenShiftProjectUIModel.java
cc @fbricon @adietish Added fresh of deployments from project node.
> [JBIDE-21385] Refresh project deployments

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/ConnectionWizardFragment.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/ServerSettingsWizardFragment.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/ServiceViewModel.java
Reset services at connection change.
Loading services at activating server settings page.
> JBIDE-21324 Server Adapter: Can finish wizard after picking connection, should not be able to

- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/explorer/BaseExplorerContentProvider.java
- plugins/org.jboss.tools.openshift.ui/plugin.xml
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/explorer/OpenShiftExplorerContentProvider.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/handler/DeleteProjectsHandler.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/models/Deployment.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/models/DeploymentResourceMapper.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/models/IAncestorable.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/models/IResourceUIModel.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/models/IResourcesUIModel.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/models/OpenShiftProjectUIModel.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/models/OpenShiftResourceUIModel.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/models/ResourcesUIModel.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/property/tabbed/BuildsPropertySection.java
Update the OpenShift explorer view when notified to changes of resources.
cc @fbricon @adietish
> [JBIDE-21444] Update explorer tree when deployments update

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/OpenShiftServer.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/OpenShiftServerBehaviour.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/OpenShiftServerPublishMethod.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/OpenShiftServerUtils.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/OpenShiftCoreActivator.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/server/resources/OpenshiftResourceChangeListener.java
and ensure publishing for special project happens
automatically
> JBIDE-21371 - add custom auto-publish thread    

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/explorer/OpenShiftExplorerContentProvider.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/job/OpenShiftJobs.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/models/DeploymentResourceMapper.java
> [JBIDE-21458] Fix blank node when adding the first deployment to a project

- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/explorer/BaseExplorerContentProvider.java
- plugins/org.jboss.tools.openshift.ui/plugin.xml
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/explorer/OpenShiftExplorerContentProvider.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/models/Deployment.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/models/DeploymentResourceMapper.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/models/IRelationCache.java
> [JBIDE-21498] Update deloyments even when creating a new one

- plugins/org.jboss.tools.openshift.core/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/OpenShiftServerBehaviour.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/OpenShiftServerPublishMethod.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/RSync.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/server/resources/OpenshiftResourceChangeListener.java
- plugins/org.jboss.tools.openshift.egit.core/src/org/jboss/tools/openshift/egit/core/EGitUtils.java
This PR is an intiial implementation for zipping / assembling wtp-style projects for deployment / rsync over to the remote pod. This patch is the best we can do for beta2, but it does suffer from several problems, which require much larger architectural changes to be 100% functional. 
Discussion on the architectural issues should be on the jira, while this can review the code specifically.
> JBIDE-21481 - initial commit for wtp-style project support

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/explorer/OpenShiftExplorerLabelProvider.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/models/Deployment.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/property/OpenShiftPropertySourceAdapterFactory.java
Deployment implements IResourceUIModel
> JBIDE-21579 Not able to delete service within the latest JBT

- plugins/org.jboss.tools.openshift.client/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.client/src/jetty-logging.properties
- plugins/org.jboss.tools.openshift.client/src/org/jboss/tools/openshift/client/internal/OpenShiftClientActivator.java
> [JBIDE-21596] divert Jetty logging to StdErr to control logging level

- plugins/org.jboss.tools.openshift.ui/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/comparators/ProjectViewerComparator.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/project/ManageProjectsWizardPage.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/comparators/ProjectViewerComparatorTest.java
> [JBIDE-21633] Sort project in dialog by importance and name

- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/wizard/KeyValueWizardPage.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/validator/LabelKeyValidator.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/common/ResourceLabelsPage.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/validator/LabelKeyValidatorTest.java
1. Finish is disabled and error message is available if key duplicates an existing key (in case of edit another one).
2. Finish is disabled and user is prompted to change data if in case of edit it remains unmodified.
> JBIDE-20997 Should not be able to create duplicative labels

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/job/DeployImageJob.java
> [JBIDE-21626] Fix deployment not triggered when deploying docker image

- plugins/org.jboss.tools.openshift.cdk.server/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/CDKConstants.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/controllers/CDKLaunchController.java
- tests/org.jboss.tools.openshift.cdk.server.test/META-INF/MANIFEST.MF
- tests/org.jboss.tools.openshift.cdk.server.test/src/org/jboss/tools/openshift/cdk/server/test/AllTestsSuite.java
- tests/org.jboss.tools.openshift.cdk.server.test/src/org/jboss/tools/openshift/cdk/server/test/internal/CDKLaunchControllerTest.java
> [JBIDE-21814] remove --provision flag from CDK launch config

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/DeployImagePage.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/DeployImageWizardModel.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/IDeployImagePageModel.java
Providing content assist based on the current input image name
Loading the sorted list of images when the Docker connection changes
Refactored the code to move the widgets creation/init in private methods
> JBIDE-21802 - Content assist for image names in "Deploy Docker Image" wizard

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/models/OpenShiftProjectCache.java
I tried to move 'adapters = createEntry(conn)' after the query to the connection for projects that may invoke request for credentials and probably change the key for it. 
Then, adapters set is always not null and can be returned.
If there is still a possibility, that cache will be changed while set adapters is initialized, then the creation of list should be changed as
adapters = getCacheFor(conn);
return adapters != null ? new ArrayList<>(adapters) : Collections.emptyList();
> JBIDE-21872 NPE is thrown on OS 3 connection without any project on fresh start of IDE

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/RSync.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/OCBinaryOperation.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/portforwarding/PortForwardingUtils.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/handler/AbstractOpenShiftCliHandler.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/job/PodLogsJob.java
> [JBIDE-21920] ensure the oc binary is set when necessary

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/property/BuildConfigPropertySource.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/newapp/ResourceDetailsContentProvider.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/property/build/BuildConfigPropertySourceTest.java
@fbricon fixes class cast exception introduced by rest client changes.
> [JBIDE-21948] fix ClassCastException for SourceBuildStrategy

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/server/resources/OpenshiftResourceChangeListener.java
Filter out changes on files that have only have a 'marker'
change, and record changes on folders.
> JBIDE-21965 - oc rsync triggered when adding/removing breakpoints

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/ServicesAndRoutingPage.java
Let them be random unused values in interval [1025..65535]
> JBIDE-21972 Improve initialization of Configure Service Ports dialog

- plugins/org.jboss.tools.openshift.core/plugin.xml
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/behavior/OpenShiftLaunchController.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/behavior/OpenShiftPublishController.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/behavior/OpenShiftShutdownController.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/server/debug/OpenShiftDebugUtils.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/core/server/OpenShiftDebugUtilsTest.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/core/server/OpenShiftSubsystemTest.java
also fixed server status in case an error occurs during startup
> [JBIDE-22033] Terminate remote debugger when stopping the server

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/OpenShiftServerUtils.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/behavior/OpenShiftLaunchController.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/behavior/OpenShiftPublishController.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/util/ResourceUtils.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/OpenShiftServerEditorModel.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/ServerSettingsWizard.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/ServerSettingsWizardFragment.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/ServerSettingsWizardPage.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/ServerSettingsWizardPageModel.java
setting the project and the service in a different manner whether the wizard
was started from explorer or "new server adapter"-wizard
> [JBIDE-21984] server adapter wizard: set project/service according to invocation

- plugins/org.jboss.tools.openshift.client/.classpath
- plugins/org.jboss.tools.openshift.client/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.client/pom.xml
cc @fbricon  can be merged after release of rest client
> [JBIDE-22030] Openshift REST client release 4.0.0.Final

- plugins/org.jboss.tools.openshift.client/log4j.properties
> [JBIDE-22111] removed stdout from log4j so that client log wont make it to Eclipse log

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/newapp/NewApplicationWizardModel.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/newapp/TemplateParametersPage.java
@adietish, @alexeykazakov care to review this respin-b candidate?
> [JBIDE-22123] disable reset button when no parameter is selected

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/BuildConfigDetailViews.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/importapp/BuildConfigWizardPage.java
Added a new BuildConfigDetailsView that displays:
- name
- namespace
-labels
- sourceURI
-outputRepositoryName
> [JBIDE-21841] Shortened repo URL in Import wizard is weird

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/OpenShiftServerUtils.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/ServerSettingsWizardPageModel.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/core/server/OpenShiftServerUtilsTest.java
> [JBIDE-22128] better detect EAP style deployments

- plugins/org.jboss.tools.openshift.ui/plugin.xml
Already applied in master. Consider merging in 4.3.x in case we respin.
cc @alexeykazakov
> [JBIDE-21991] remove 'Server Adapter...' menu from Routes context menu

- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/ui/internal/CDKServerWizardFragment.java
https://issues.jboss.org/browse/JBDS-3574
CDK username pulldown field is not tall enough
> CDK username pulldown field is not tall enough

- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/connection/ConnectionWizardPage.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/DeployImagePage.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/DeployImageWizard.java
Add a first page to manage Openshift connections
> [JBIDE-20597] Add connection management to deploy image wizard

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/newapp/TemplateListPage.java
Improved creation of comparator for Select template page
> JBIDE-22160 Order of project in New OS 3 Application wizard is not alphanumeric

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/util/ResourceUtils.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/ServerSettingsWizardPageModel.java
- tests/org.jboss.tools.openshift.test/META-INF/MANIFEST.MF
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/common/core/util/TestProject.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/core/util/ResourceUtilsTest.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/server/ServerSettingsWizardPageModelTest.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/util/ResourceMocks.java
> [JBIDE-22268] implemented test for the server adapter

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/newapp/NewApplicationWizard.java
@jcantrill , please take a look.
> JBIDE-22301 NPE in new OS application from eclipse project with no remote git reference.

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/preferences/OCBinaryValidator.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/preferences/OpenShiftPreferencePage.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/internal/core/preferences/OCBinaryValidatorTest.java
> [JBIDE-22275] Make oc version parsing more robust

- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/utils/TableViewerBuilder.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/newapp/fromtemplate/ApplicationSourceFromTemplateModel.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/newapp/fromtemplate/TemplateParametersPage.java
1. Button 'Reset All' is added.
2. Modified values are rendered in italics.
3. Buttons 'Reset' and 'Reset All' are enabled only when they can reset something.
> JBIDE-22265 Application wizard: Allow users to reset values of all template parameters

- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/common/core/util/VariablesHelperTest.java
> [JBIDE-22295] VariablesHelperTest failing under Windows

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/importapp/ImportApplicationWizard.java
[JBIDE-22183] Local folder not saved when creating an Openshift application
> [JBIDE-22183] Local folder not saved when creating an Openshift application

- plugins/org.jboss.tools.openshift.common.core/src/org/jboss/tools/openshift/common/core/connection/AbstractConnectionPersistency.java
- plugins/org.jboss.tools.openshift.core/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/connection/Connection.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/connection/ConnectionPersistency.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/connection/IOpenShiftConnection.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/preferences/IOpenShiftCorePreferences.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/preferences/OpenShiftCorePreferences.java
- plugins/org.jboss.tools.openshift.express.core/src/org/jboss/tools/openshift/express/internal/core/connection/ExpressConnectionPersistency.java
- tests/org.jboss.tools.openshift.express.test/src/org/jboss/tools/openshift/express/test/core/connection/ExpressConnectionPersistencyTest.java
- tests/org.jboss.tools.openshift.test/META-INF/MANIFEST.MF
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/AllTestsSuite.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/common/core/util/TestProject.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/core/connection/ConnectionPersistencyTest.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/internal/OpenShiftTestActivator.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/internal/core/portforwarding/PortForwardingUtilsTest.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/internal/core/portforwarding/package-info.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/internal/core/preferences/OCBinaryValidatorTest.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/internal/core/preferences/OpenShiftCorePreferencesTest.java
Add a mechanism to load and save advanced properties of a connection
cc @adietish @fbricon
> [JBIDE-22358] Add load and presist of advanced properties for a connection

- plugins/org.jboss.tools.openshift.ui/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/connection/OAuthDetailView.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/wizard/connection/OAuthDetailViewTest.java
> [JBIDE-22360] Extract OAuth token from the New Connection wizard

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/connection/OAuthDetailView.java
> [JBIDE-22363] open Token page in embedded browser on OSX

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/common/AbstractProjectPage.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/DeployImagePage.java
> [JBIDE-22260] - Change 'Manage projects...' links to "New..." buttons

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/OpenshiftUIConstants.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/common/AbstractProjectPage.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/newapp/ApplicationSourceListPage.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/newapp/IApplicationSourceListPageModel.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/newapp/NewApplicationWizardModel.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/resource/IResourcePayloadPageModel.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/resource/NewResourceWizard.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/resource/ResourcePayloadPage.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/wizard/newapp/NewApplicationWizardModelTest.java
[JBIDE-22190] Application wizard: Support "URL" templates to create a new application
- Added a new tab to the template page to allow specify a template by URL
> [JBIDE-22190] Application wizard: Support "URL" templates to create a new application

- plugins/org.jboss.tools.openshift.common.ui/plugin.xml
- plugins/org.jboss.tools.openshift.common.ui/schema/org.jboss.tools.openshift.ui.connectionEditor.advanced.exsd
- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/connection/AdvancedConnectionEditorsStackedView.java
- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/connection/ConnectionWizardPage.java
- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/connection/IAdvancedConnectionPropertiesEditor.java
- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/utils/DialogAdvancedPart.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/ICommonAttributes.java
- plugins/org.jboss.tools.openshift.ui/plugin.xml
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/validator/URLValidator.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/connection/AdvancedConnectionEditor.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/AllTestsSuite.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/validator/URLValidatorTest.java
> [JBIDE-22314] Allow defining an image registry URL for a connection

- plugins/org.jboss.tools.openshift.common.core/src/org/jboss/tools/openshift/internal/common/core/job/JobChainBuilder.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/core/JobChainBuilderTest.java
Added solution for JBIDE-22412 Enhance JobChainBuilder with conditions for starting the next job
by means of a progress monitor.
> JBIDE-22412 Enhance JobChainBuilder with conditions for starting the next job

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/OpenShiftServerEditorSection.java
Depends on https://github.com/jbosstools/jbosstools-openshift/pull/1188
> JBIDE-22413 Connection Editor: dont launch further jobs if editor is already closed

- features/org.jboss.tools.openshift.cdk.test.feature/build.properties
- features/org.jboss.tools.openshift.cdk.test.feature/feature.properties
- features/org.jboss.tools.openshift.cdk.test.feature/feature.xml
- features/org.jboss.tools.openshift.cdk.test.feature/pom.xml
- features/pom.xml
- plugins/org.jboss.tools.openshift.cdk.server/about.html
- plugins/org.jboss.tools.openshift.cdk.server/about.properties
- plugins/org.jboss.tools.openshift.cdk.server/plugin.properties
- plugins/org.jboss.tools.openshift.cdk.server/plugin.xml
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/CDKServer.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/detection/CDKRuntimeDetector.java
- site/category.xml
- tests/org.jboss.tools.openshift.cdk.server.test/plugin.properties
This is an initial PR.  I may need to externalize the strings before it's suitable for push, but this seems to cover all expected bases.
> JBIDE-22431 - rename cdk plugin and feature in UI elements

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/models/PortSpecAdapter.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/common/EnvironmentVariable.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/ServicePortAdapter.java
- tests/org.jboss.tools.openshift.test/resources/failed_ImageStreamImport.json
- tests/org.jboss.tools.openshift.test/resources/openshift3_jenkins_1_rhel7_ImageStreamImport.json
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/wizard/deployimage/DeployImageWizardModelTest.java
> [JBIDE-22313] Deploy Docker Image wizard: need unit tests

- features/org.jboss.tools.openshift.egit.integration.feature/.project
- features/org.jboss.tools.openshift.egit.integration.test.feature/.project
- features/org.jboss.tools.openshift.feature/.project
- features/org.jboss.tools.openshift.test.feature/.project
- plugins/org.jboss.tools.openshift.cdk.server/.project
- plugins/org.jboss.tools.openshift.cdk.server/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/listeners/CDKDockerUtility.java
- plugins/org.jboss.tools.openshift.client/.classpath
- plugins/org.jboss.tools.openshift.client/.project
- plugins/org.jboss.tools.openshift.common.core/.project
- plugins/org.jboss.tools.openshift.common.ui/.project
- plugins/org.jboss.tools.openshift.core/.project
- plugins/org.jboss.tools.openshift.egit.core/.project
- plugins/org.jboss.tools.openshift.egit.ui/.project
- plugins/org.jboss.tools.openshift.express.client/.project
- plugins/org.jboss.tools.openshift.express.core/.project
- plugins/org.jboss.tools.openshift.ui/.project
- tests/org.jboss.tools.openshift.cdk.server.test/.project
- tests/org.jboss.tools.openshift.egit.test/.project
- tests/org.jboss.tools.openshift.test/.project
Signed-off-by: Xavier Coulon <xcoulon@redhat.com>
> JBIDE-22463 - Update CDK code after API change in Docker tooling

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/common/EnvironmentVariablePage.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/DeploymentConfigPage.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/newapp/fromimage/BuildConfigPage.java
cc @fbricon @mlabuda 
Modified labels per issue to be more explicit.
> [JBIDE-22454] Fix env var labels on new-app pages to be more explicit

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/ServicesAndRoutingPage.java
cc @fbricon 
Updates the tooltip to provide additional info
> [JBIDE-20601] Add info to deploy image route tooltip

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/preferences/OCBinaryValidator.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/OpenShiftUIMessages.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/OpenShiftUIMessages.properties
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/OpenShiftServerEditorModel.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/ServerSettingsWizardPage.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/ServerSettingsWizardPageModel.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/internal/core/preferences/OCBinaryValidatorTest.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/server/ServerSettingsWizardPageModelTest.java
> [JBIDE-22432] If oc binary can't be located, then Internal Error is spawned in the server adapter wizard

- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/listeners/CDKOpenshiftUtility.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/listeners/ConfigureDependentFrameworksListener.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/listeners/ServiceManagerEnvironment.java
- tests/org.jboss.tools.openshift.cdk.server.test/META-INF/MANIFEST.MF
- tests/org.jboss.tools.openshift.cdk.server.test/src/org/jboss/tools/openshift/cdk/server/test/AllTestsSuite.java
- tests/org.jboss.tools.openshift.cdk.server.test/src/org/jboss/tools/openshift/cdk/server/test/internal/CDKOpenshiftUtilityTest.java
- tests/org.jboss.tools.openshift.cdk.server.test/src/org/jboss/tools/openshift/cdk/server/test/internal/ServiceManagerParsingTest.java
Tested with service manager 1.0.1,  1.0.2,  and 1.1.0.
> JBIDE-22575 - Read docker registry from service-manager

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/newapp/ApplicationSourceListPage.java
One multi-validator may not be bound to several widgets
if each widget may have its own status message.
If change in one value may influence validation of another,
we may pass and poll all observables to all interested validators
so that they will be bound, but each validator should return status
for its own widget (bound to one of validated observables).
The rule is: we need as many validators as we the number of status
messages that may/should be displayed at the same time. The reason
is: one validator returns one status.
> JBIDE-22511 Application wizard: project without git remote is initially decorated with a "required" decorator, not the warning decoration

- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/connection/ConnectionWizardPageModel.java
Remove useless first part of the error message
> [JBIDE-22115] Connection wizard: Truncated error message display connecting to server

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/portforwarding/PortForwardingUtils.java
Suppress TCP connection establishment to checked port
> [JBIDE-22442] Port Forwarding wizard: When managing forwarding ports, UI is unresponsive when playing with find free local ports

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/connection/Connection.java
- Removed useless message when authentication failed
> [JBIDE-21871] - Weird message in error log when connecting to cdk openshift - Unauthorized

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/OpenShiftCoreMessages.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/OpenShiftCoreMessages.properties
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/behavior/OpenShiftLaunchController.java
- Add fake process to OS3 server adapter launch
> [JBIDE-22152] - Server Adapter, Debugging: Unknown launch is left in Debug view after deletion of an OS 3 server adapter

- plugins/org.jboss.tools.openshift.common.core/src/org/jboss/tools/openshift/common/core/connection/ConnectionURL.java
- plugins/org.jboss.tools.openshift.common.core/src/org/jboss/tools/openshift/internal/common/core/job/JobChainBuilder.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/OpenShiftServerUtils.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/OpenShiftServerEditorSection.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/core/JobChainBuilderTest.java
@fbricon @jeffmaury @bdshadow plz review
> [JBIDE-22639] display proper err & keep editor disabled if no connection exists

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/OpenShiftServerAdapterFactory.java
- tests/org.jboss.tools.openshift.test/META-INF/MANIFEST.MF
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/core/server/OpenShiftServerAdapterFactoryTest.java
> [JBIDE-22698] fix Live Reload support by fixing OpenShift Server adapter factory

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/DeployImagePage.java
> [JBIDE-22654] - If image name ends with spaces, deploy is not possible

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/WatchManager.java
- plugins/org.jboss.tools.openshift.ui/plugin.properties
- plugins/org.jboss.tools.openshift.ui/plugin.xml
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/models/ConnectionWrapper.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/property/tabbed/TemplatesPropertySection.java
> [JBIDE-22457] - Template are not displayed in property views for an Openshift project

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/OpenShiftUIMessages.properties
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/handler/DeleteResourceHandler.java
- Change dialog title when projects
> [JBIDE-22632] - Spurious message due to incorrect I18N

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/handler/OpenInWebConsoleHandler.java
> [JBIDE-22622] - Opening the Web Console in the embedded browser (by default) results in error

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/dockerutils/PushImageToRegistryJob.java
> [JBIDE-22764] maintain compatibility between Neon.0 and Neon.1 versions of Docker tooling

- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/ui/internal/view/CDKActionProvider.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/explorer/OpenShiftExplorerContentProvider.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/models/AbstractOpenshiftUIElement.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/models/OpenshiftUIModel.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/explorer/OpenShiftExplorerContentProviderTest.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/models/OpenShiftProjectCacheTest.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/models/RefreshTest.java
when "Show in -> OS Exlporer" on CDK in Servers view
> jbide-22684: show up login prompt only for appropriate OS connection

- plugins/org.jboss.tools.openshift.common.ui/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/OpenShiftCommonUIMessages.java
- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/OpenShiftCommonUIMessages.properties
- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/application/importoperation/AbstractProjectImportOperation.java
- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/application/importoperation/GeneralProjectImportOperation.java
- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/application/importoperation/MavenProjectImportOperation.java
- Add warning dialog for Maven projects
- Cleanup workspace in case of projects already exists
> [JBIDE-22079] - Import wizard: Error when import a project already existing in workspace

- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/connection/ConnectionWizardPageModel.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/common/ui/utils/ConnectionWizardPageModelTest.java
> {JBIDE-22645] - Pre-select OpenShift 3 in New OpenShift Connection wizard

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/connection/ConnectionFactory.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/connection/ConnectionProperties.java
- Change max concurrent web socket calls to 1000
> [JBIDE-22861] - Explorer: Pod is not refreshed (watch problem with new ohttp based rest client)

- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/common/ui/wizard/AbstractApplicationWorkbenchWizard.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/newapp/NewApplicationWizard.java
> [JBIDE-22704] - Application Wizard: Application based on builder images do not have prefilled configuration

- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/OpenShiftCommonUIMessages.java
- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/OpenShiftCommonUIMessages.properties
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/ServerSettingsWizardPage.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/ServerSettingsWizardPageModel.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/importapp/ImportApplicationWizard.java
> [JBIDE-22621] - Server adapter wizard: should be able to import projects to my workspace

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/connection/OAuthDetailView.java
> [JBIDE-22806] - Connection wizard: "Finish" is enabled even though I didnt oauth authenticate to pick a token

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/ICommonAttributes.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/connection/Connection.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/connection/IOpenShiftConnection.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/job/DeployImageJob.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/connection/AdvancedConnectionEditor.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/newapp/ApplicationSourceTreeItems.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/job/DeployImageJobTest.java
> [JBIDE-23014] - Allow connections to configure the cluster namespace from which to get clusterwide templates

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/util/ResourceUtils.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/core/util/ResourceUtilsTest.java
This depends  on #1318 (openshift-restclient-java 5.2.0-SNAPSHOT) being merged first
> [JBIDE-23205]  allow to get replication controllers for a given service	

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/OpenShiftServerEditorSection.java
https://issues.jboss.org/browse/JBIDE-23177
>  JBIDE-23177 - Server Editor: Combo items have wrong size

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/common/AbstractProjectPage.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/DeployImagePage.java
https://issues.jboss.org/browse/JBIDE-22912
Deploy Docker Wizard: Inappropriate project combo size
> JBIDE-22912 - Deploy Docker Wizard: Inappropriate project combo size

- plugins/org.jboss.tools.openshift.ui/.classpath
- plugins/org.jboss.tools.openshift.ui/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.ui/pom.xml
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/OpenShiftUIMessages.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/OpenShiftUIMessages.properties
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/job/DeployImageJob.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/DeployImageWizardModel.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/IServiceAndRoutingPageModel.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/ServicesAndRoutingPage.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/wizard/deployimage/DeployImageWizardModelTest.java
> [JBIDE-23147] - application wizard: Support optional host when route is created

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/DockerConfigMetaData.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/wizard/deployimage/DeployImageWizardModelTest.java
> [JBIDE-23362] - Failed test because of JBIDE-22916

- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/controllers/CDKLaunchController.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/listeners/CDKOpenshiftUtility.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/listeners/ConfigureDependentFrameworksListener.java
No. 
Yes
Yes
Yes
No
No
Yes
Yes
Yes
> JBIDE-23300 - need to connect the openshift connection in order to save it. 

- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/TableCellMouseAdapter.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/ServicesAndRoutingPage.java
> JBIDE-23353 Deploy Docker Wizard: Enable checking "Used by route"

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/ServicesAndRoutingPage.java
> [JBIDE-23354] - Deploy Docker Wizard: Reset of port mapping whille at least 1 default is present causes NPE

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/util/ResourceUtils.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/handler/ScaleDeploymentHandler.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/core/util/ResourceUtilsTest.java
- Is this a blocking issue or new feature? If yes, QE needs to +1 this PR
- Are method-/class-/variable-names meaningful?
- Are methods concise, not too long?
- Are catch blocks catching precise Exceptions only (no catch all)?
- Are there unit-tests?
- Are there integration tests (or at least a jira to tackle these)?
- Is the non-happy path working, too?
- Are other parts that use the same component still working fine?
- Does it work?
> [JBIDE-23030] fix scaling pods starting from a service

- plugins/org.jboss.tools.openshift.common.core/src/org/jboss/tools/openshift/common/core/utils/X509CertificateParser.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/preferences/SSLCertificatesPreference.java
This PR has not been appropriately tested. Please test it before merging.
> JBIDE-23208 - fix ssl certificate validity parser

- plugins/org.jboss.tools.openshift.ui/plugin.xml
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/dialog/SelectRouteDialog.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/handler/EditDefaultRouteHandler.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/handler/OpenInWebBrowserHandler.java
> JBIDE-23360

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/WatchManager.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/job/DeleteResourceJob.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/job/OpenShiftJobs.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/models/ConnectionWrapper.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/models/ResourceCache.java
- Is this a blocking issue or new feature? yes
- Are method-/class-/variable-names meaningful? 
- Are methods concise, not too long?
- Are catch blocks catching precise Exceptions only (no catch all)?
- Are there unit-tests?
- Are there integration tests (or at least a jira to tackle these)?
- Is the non-happy path working, too?
- Are other parts that use the same component still working fine?
- Does it work?
> JBIDE-23184: Add Capability to Watch Projects

- plugins/org.jboss.tools.openshift.client/.classpath
- plugins/org.jboss.tools.openshift.client/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.client/pom.xml
> [JBIDE-23378] bumped openshift-restclient-java to 5.2.0.Final

- plugins/org.jboss.tools.openshift.client/.classpath
- plugins/org.jboss.tools.openshift.client/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.client/pom.xml
> [JBIDE-23435] bumped openshift-restclient-java to 5.3.0.Final

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/RSync.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/WatchManager.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/models/ConnectionWrapper.java
> jbide-23740: Server Adapter: stuck restarting in debug mode

- features/org.jboss.tools.openshift.egit.integration.feature/pom.xml
> Remove not necessary version in pom

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/handler/PodLogsHandler.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/AllTestsSuite.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/handler/PodLogsHandlerTest.java
- Added Completed as supported pod state
> JBIDE-23622 - Build Log: impossible to get logs once the build pod is completed

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/newapp/fromimage/ApplicationSourceFromImageModel.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/newapp/fromtemplate/ApplicationSourceFromTemplateModel.java
> [JBIDE-23639] - Application wizard: Templates parameters show wrong values if using existing eclipse project

- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/VagrantPoller.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/controllers/CDKLaunchController.java
> [JBDS-4227] cleaning up code

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/models/ConnectionWrapper.java
> [JBIDE-23707] clarified loading job messages in explorer

- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/detection/CDKRuntimeDetector.java
No. 
Just added some Null checks
* Are there unit-tests?   No
* Are there integration tests (or at least a jira to tackle these)?  No
* Is the non-happy path working, too?  Yes
* Are other parts that use the same component still working fine? Yes
Yes
> JBIDE-23637 - NPE in cdk runtime detection

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/handler/ScaleDeploymentHandler.java
> [JBIDE-23662] removed superfulous 2nd scaling job

- plugins/org.jboss.tools.openshift.core/build.properties
- plugins/org.jboss.tools.openshift.express.core/build.properties
- plugins/org.jboss.tools.openshift.js/build.properties
- plugins/org.jboss.tools.openshift.ui/build.properties
- tests/org.jboss.tools.openshift.cdk.server.test/build.properties
- tests/org.jboss.tools.openshift.express.test/build.properties
- tests/org.jboss.tools.openshift.test/build.properties
> [JBIDE-23767] added src.includes and src.excludes to build.propertie(s)

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/handler/ScaleDeploymentHandler.java
> [JBIDE-23765] Scale To: showing deployment that is to be scaled

- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/requirement/OpenShiftResources.java
This will be used in future integration tests as part of https://issues.jboss.org/browse/JBIDE-23321
> Defines NODEJS_GIT_NAME string for nodejs service template

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/handler/ScaleDeploymentContributionItem.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/handler/ScaleDeploymentHandler.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/handler/ScaleDeploymentHandlerTest.java
> [JBIDE-23764] Scale To: display current (not desired) replicas

- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/utils/OpenShiftLabel.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/utils/SecureStorage.java
> (itests, test-framework) Handle "Password Hint needed" shell when it pops up.

- test-framework/org.jboss.tools.cdk.reddeer/build.properties
- test-framework/org.jboss.tools.openshift.reddeer/build.properties
> Added missing directives for test-frameworks build.properties.

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/property/BuildConfigPropertySource.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/property/BuildPropertySource.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/property/ResourcePropertySource.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/property/ResourcePropertySourceTest.java
> [JBIDE-23841] added (resource) "Kind" to "Details" properties-tab

- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/listeners/MinishiftServiceManagerEnvironmentLoader.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/behavior/OpenShiftLaunchController.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/OpenShiftCoreActivator.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/OpenshiftServerLifecycleListener.java
Enhancement to fix annoying thing
* Are method-/class-/variable-names meaningful?  Yes
* Are methods concise, not too long?  Yes
* Are catch blocks catching precise Exceptions only (no catch all)? Yes
* Are there unit-tests? No
* Are there integration tests (or at least a jira to tackle these)? No
* Is the non-happy path working, too? I think so? Might need someone else to test more. 
* Are other parts that use the same component still working fine? Yes
Yes
> JBIDE-23782 - wait for build pods to complete and other pods to be running

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/OpenShiftUIMessages.properties
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/handler/DeleteResourceHandler.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/utils/OpenShiftLabel.java
> [JBIDE-23886] tell the user what type of resource we're deleting

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/behavior/OpenShiftLaunchController.java
- Fix unnecessary wait when no connection
> [JBIDE-22228] - NPE when deploying to Openshift EAP

- plugins/org.jboss.tools.openshift.cdk.server/plugin.properties
- plugins/org.jboss.tools.openshift.cdk.server/plugin.xml
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/CDK3Server.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/controllers/CDK3LaunchController.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/ui/internal/AbstractLocationSection.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/ui/internal/CDK3ServerWizardFragment.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/ui/internal/CDKServerWizardFragment.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/ui/internal/MinishiftLocationSection.java
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR  - Doesn't need +1 
* Are method-/class-/variable-names meaningful? yes
* Are methods concise, not too long? yes
* Are catch blocks catching precise Exceptions only (no catch all)? yes
* Are there unit-tests? no
* Are there integration tests (or at least a jira to tackle these)? no
* Is the non-happy path working, too? yes
* Are other parts that use the same component still working fine?yes
yes it works
> JBIDE-23896 - allow user to choose hypervisor as first class option

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/util/ResourceUtils.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/handler/ScaleDeploymentContributionItem.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/handler/ScaleDeploymentHandler.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/models/ServiceResourceMapper.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/ServerSettingsWizardPage.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/ServerSettingsWizardPageModel.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/utils/ResourceWrapperUtils.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/core/util/ResourceUtilsTest.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/handler/ScaleDeploymentHandlerTest.java
> [JBIDE-23817] scale deployment configs (was: replication controller)

- plugins/org.jboss.tools.openshift.client/pom.xml
> [JBIDE-23883] removed enforcer kill-switch

- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/controllers/CDKLaunchUtility.java
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR no, bug fix
* Are method-/class-/variable-names meaningful? yes
* Are methods concise, not too long? yes
* Are catch blocks catching precise Exceptions only (no catch all)? yes
* Are there unit-tests?no
* Are there integration tests (or at least a jira to tackle thes e)? no
* Is the non-happy path working, too? yes
* Are other parts that use the same component still working fine? yes
* Does it work?yes
> Stream reader for external process inconsistant

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/OpenShiftServerUtils.java
I think it's worth starting to watch projects when we need a service in the Server Adapter.
@adietish @jeffmaury this patch fixes the bug for me. Please, test it
> JBIDE-23903: Start watching resources from openshift server adapter

- plugins/org.jboss.tools.openshift.client/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.client/pom.xml
Reverts jbosstools/jbosstools-openshift#1428
> Revert "JBIDE-24010 bump openshift.client to 3.3.100..."

- features/org.jboss.tools.openshift.feature/feature.xml
- features/org.jboss.tools.openshift.feature/pom.xml
- plugins/org.jboss.tools.openshift.client/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.client/pom.xml
- plugins/org.jboss.tools.openshift.core/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.core/pom.xml
> [JBIDE-24010] bump core and client plugins

- features/org.jboss.tools.openshift.cdk.feature/feature.xml
- features/org.jboss.tools.openshift.cdk.feature/pom.xml
- features/org.jboss.tools.openshift.feature/feature.xml
- features/org.jboss.tools.openshift.feature/pom.xml
- plugins/org.jboss.tools.openshift.cdk.server/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.cdk.server/pom.xml
- plugins/org.jboss.tools.openshift.client/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.client/pom.xml
- plugins/org.jboss.tools.openshift.core/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.core/pom.xml
> [JBIDE-24010] bump core, client, cdk and features

- plugins/org.jboss.tools.openshift.ui/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.ui/pom.xml
> [JBIDE-23890] bump ui plugin

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/OpenShiftServerEditorSection.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/SelectServiceWizard.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/ServerSettingsWizardPageModel.java
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR - very annoying UI stuff
* Are method-/class-/variable-names meaningful? yes
* Are methods concise, not too long? yes
* Are catch blocks catching precise Exceptions only (no catch all)? yes
* Are there unit-tests? no, it's UI
* Are there integration tests (or at least a jira to tackle these)? idk
* Is the non-happy path working, too? kinda... it's better than it was?
* Are other parts that use the same component still working fine? yes
* Does it work? mostly. 
First, the code was needlessly complex. It was chaining jobs when it didn't need to. It could do it all in one job and accumulate the results.  Also, anonymous inner functions are ok if they're short, but not when it starts to clutter the code. 
Eventually I …
> JBIDE-23812 - fix loading and undo situation for server editors

- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/utils/UIUtils.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/SelectServiceWizard.java
> [JBIDE-24033] allow users to double click to select a service

- plugins/org.jboss.tools.openshift.common.ui/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.common.ui/pom.xml
> [JBIDE-24033] bump common.ui in jbosstools-4.4.x since it changed

- features/org.jboss.tools.openshift.express.feature/feature.xml
> [JBIDE-24033] bumping express feature which includes bumped common.ui

- features/org.jboss.tools.openshift.express.feature/feature.xml
- features/org.jboss.tools.openshift.express.feature/pom.xml
> [JBIDE-24033] bump express feature which includes bumped common.ui

- features/org.jboss.tools.openshift.js.feature/feature.xml
- features/org.jboss.tools.openshift.js.feature/pom.xml
- plugins/org.jboss.tools.openshift.js/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.js/pom.xml
> [JBIDE-23490] bumping openshift.js and js.feature

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/OpenShiftServerBehaviour.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/OpenShiftServerUtils.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/behavior/OpenShiftLaunchController.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/server/debug/DebuggingContext.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/server/debug/OpenShiftDebugUtils.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/core/server/OpenShiftDebugUtilsTest.java
> [JBIDE-23961] dont consider dev_mode as "debug is enabled"

- features/org.jboss.tools.openshift.test.feature/feature.xml
- features/org.jboss.tools.openshift.test.feature/pom.xml
- tests/org.jboss.tools.openshift.test/META-INF/MANIFEST.MF
- tests/org.jboss.tools.openshift.test/pom.xml
> [JBIDE-23961] bump test plugin and test feature

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/importapp/GitCloningWizardPage.java
> [JBIDE-23780] - Import Application: uncheck "Use default clone destination" wont recheck if I removed the folder that it''s complaining about

- plugins/org.jboss.tools.openshift.cdk.server/plugin.xml
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/CDKConstants.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/CDK3Server.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/CDKServer.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/controllers/CDK3LaunchController.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/detection/AbstractCDKRuntimeDetector.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/detection/CDK3RuntimeDetector.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/detection/CDKRuntimeDetector.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/ui/internal/CDK3ServerWizardFragment.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/ui/internal/MinishiftLocationSection.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/ui/internal/detection/MissingMinishiftResolutionProvider.java
> JBIDE-24081 - Add runtime detection support for cdk3

- plugins/org.jboss.tools.openshift.cdk.server/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/detection/CDK3RuntimeDetector.java
> JBIDE-24122 - read vm-driver from ~/.minishift/config/config.json

- plugins/org.jboss.tools.openshift.cdk.server/META-INF/MANIFEST.MF
Probably mistake during cherry-picking to 4.4.x branch.
> Fix for wrong version of dmr plugin is required (from master).

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/OpenShiftServerUtils.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/behavior/OpenShiftLaunchController.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/server/debug/OpenShiftDebugUtils.java
- plugins/org.jboss.tools.openshift.js/src/org/jboss/tools/openshift/js/launcher/NodeDebugLauncher.java
> [JBIDE-24083] make sure dev_mode is always on for nodejs apps

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/connection/Connection.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/behavior/OpenShiftLaunchController.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/WatchManager.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/server/debug/OpenShiftDebugUtils.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/util/ResourceUtils.java
- plugins/org.jboss.tools.openshift.egit.core/src/org/jboss/tools/openshift/egit/core/EGitUtils.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/property/OpenShiftResourceDocumentProvider.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/importapp/ImportApplicationWizardModel.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/core/server/OpenShiftDebugUtilsTest.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/core/util/ResourceUtilsTest.java
> [JBIDE-24183] corrected tests for Debugging enablement in context

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/newapp/ResourceDetailsContentProvider.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/newapp/ResourceDetailsLabelProvider.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/server/ServerSettingsWizardPageModelTest.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/wizard/newapp/ResourceDetailsContentProviderTest.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/util/ResourceMocks.java
> [JBIDE-24232] dont NPE on unknown build strategies

- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/wizard/newapp/NewApplicationWizardModelTest.java
> Fix broken unit test

- plugins/org.jboss.tools.openshift.client/.classpath
- plugins/org.jboss.tools.openshift.client/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.client/build.properties
- plugins/org.jboss.tools.openshift.client/pom.xml
- plugins/org.jboss.tools.openshift.common.core/src/org/jboss/tools/openshift/common/core/utils/StringUtils.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/property/BuildConfigPropertySource.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/newapp/ResourceDetailsContentProvider.java
> [JBIDE-24242] display jenkins pipleline in app wizard and properties

- test-framework/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/ui/wizard/NewCDK3ServerContainerWizardPage.java
- test-framework/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/ui/wizard/NewCDKServerContainerWizardPage.java
- test-framework/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/ui/wizard/NewServerContainerWizardPage.java
> JBIDE-24003 Extended CDK UI integration tests to accept CDKv3 server adapter differences

- plugins/org.jboss.tools.openshift.client/pom.xml
> [JBIDE-24295] disable enforcer until we release final client

- plugins/org.jboss.tools.openshift.common.core/build.properties
> [JBIDE-24030] provide bundle name and vendor in built os.common.core

- test-framework/org.jboss.tools.openshift.reddeer/META-INF/MANIFEST.MF
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/preference/page/JavaDebugPreferencePage.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/requirement/OpenShiftResources.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/utils/OpenShiftLabel.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/view/resources/ServerAdapter.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/view/resources/Service.java
> JBIDE-24016 -ITests: Possibility to create server adapter from service

- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/connection/ConnectionWizardPage.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/connection/ConnectionEditor.java
> JBIDE-24389 - Changed style for combos in New Connection wizard.

- test-framework/org.jboss.tools.openshift.reddeer/META-INF/MANIFEST.MF
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/requirement/OpenShiftConnectionRequirement.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/requirement/OpenShiftProjectRequirement.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/requirement/OpenShiftServiceRequirement.java
for more pleasant cleaning experience in Itests
> JBIDE-24387 Implement cleanup for reddeer requirements

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/OpenShiftServerEditorSection.java
> [JBIDE-24415] displaying resource type as label in server ed

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/OpenShiftServerEditorSection.java
Cherry pick of https://github.com/jbosstools/jbosstools-openshift/pull/1498.
> [JBIDE-24415] displaying resource type as label in server editor (#1498)

- plugins/org.jboss.tools.openshift.client/.classpath
- plugins/org.jboss.tools.openshift.client/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.client/pom.xml
> [JBIDE-24295] using openshift-restclient-java 5.6.0.Final

- plugins/org.jboss.tools.openshift.common.core/src/org/jboss/tools/openshift/common/core/connection/IConnectionFactory.java
- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/connection/BaseConnectionEditor.java
- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/connection/ConnectionEditorsStackedView.java
- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/connection/ConnectionWizardPage.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/connection/ConnectionFactory.java
- plugins/org.jboss.tools.openshift.express.core/src/org/jboss/tools/openshift/express/internal/core/connection/ExpressConnectionFactory.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/common/core/connection/ConnectionsFactoryTest.java
> [JBIDE-24383] offer a signup link in conn wizard for OpenShift3

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/newapp/ApplicationSourceListPage.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/newapp/NewApplicationWizard.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/newapp/NewApplicationWizardModel.java
> [JBIDE-23473] new app wiz: load/validate local template upon "Next"

- tests/org.jboss.tools.openshift.egit.test/src/org/jboss/tools/openshift/egit/internal/test/EGitUtilsTest.java
Beautified version of [the previous PR](https://github.com/jbosstools/jbosstools-openshift/pull/1503) - nothing superfluous.
This linked commit was built successfully 3 times in Jenkins. So if the build for the current PR is also finished successfully, please, merge it.
> jbide-24440: fix EGit test failures

- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/ui/internal/CDK3ServerWizardFragment.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/ui/internal/CDKServerWizardFragment.java
> Typo in requries -> requires

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/DeployImageWizardModel.java
> JBIDE-24488 - fix openshift tools for changed TP

- plugins/org.jboss.tools.openshift.client/.classpath
- plugins/org.jboss.tools.openshift.client/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.client/build.properties
- plugins/org.jboss.tools.openshift.client/pom.xml
> [JBIDE-23862] prefs: dont allow oc on path with " "

- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/requirement/OpenShiftServiceRequirement.java
Service requirement can now load template from a specified path or URL.
- template=/path/to/template.json for local file
- template=URL/to/template.json for remote files
@rhopp care to take a look?
> JBIDE-24452 ITests: Support local templates in ServiceRequirement

- pom.xml
> jbide-24229: remove default activation of the quality profile

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/DeployImageWizardModel.java
> JBIDE-24481 - Deploy Image wizard: new project is not selected nor available in projects combo

- test-framework/org.jboss.tools.cdk.reddeer/META-INF/MANIFEST.MF
- test-framework/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/preferences/OpenShift3SSLCertificatePreferencePage.java
- test-framework/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/server/ui/CDEServer.java
- test-framework/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/server/ui/CDEServersView.java
- test-framework/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/server/ui/editor/CDEServerEditor.java
- test-framework/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/server/ui/editor/CDK3ServerEditor.java
- test-framework/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/server/ui/editor/CDKServerEditor.java
- test-framework/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/server/ui/wizard/CredentialsWizardPage.java
- test-framework/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/server/ui/wizard/NewCDK3ServerContainerWizardPage.java
- test-framework/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/server/ui/wizard/NewCDKServerContainerWizardPage.java
- test-framework/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/server/ui/wizard/NewServerContainerWizardPage.java
- code smells reparation from sonarcloud.io
- added new reddeer Server Editor representation
- stabilization changes (extending wait time for server to start)
* new feature: QE needs to +1 this PR
* Are there unit-tests? No
* Are there integration tests (or at least a jira to tackle these)? Yes
* Is the non-happy path working, too? 
* Does it work? Yes
> Updates to CDK New Server Wizard reddeer plugin

- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/requirement/OpenShiftResources.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/utils/SecureStorage.java
> Switched to remote nodejs-example template & secure storage tweak.

- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/condition/AmountOfResourcesExists.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/requirement/OpenShiftResources.java
> Switch to eap70 template & add constructor for AmountOfResourcesExists.

- plugins/org.jboss.tools.openshift.client/.classpath
- plugins/org.jboss.tools.openshift.client/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.client/pom.xml
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/connection/Connection.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/connection/IOpenShiftConnection.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/property/ConnectionPropertySource.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/property/ConnectionPropertySourceTest.java
please, merge only after https://github.com/openshift/openshift-restclient-java/pull/278 is merged
> jbide-24539: Explorer, Properties: User should be able to see what

- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/common/ui/wizard/AbstractApplicationWorkbenchWizard.java
> JBIDE-19604 - improvement to new application wizard wrt secure storage

- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/controllers/AbstractCDKLaunchController.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/controllers/AbstractCDKShutdownController.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/controllers/CDK3LaunchController.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/controllers/CDK3ShutdownController.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/controllers/CDKLaunchController.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/controllers/CDKLaunchUtility.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/controllers/CDKShutdownController.java
> JBIDE-24587 - switch cdk3 to console view

- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/detection/MinishiftVersionLoader.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/ui/internal/CDK3ServerWizardFragment.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/ui/internal/MinishiftLocationSection.java
> JBIDE-24682 - adjust to changes in cdk version output

- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/listeners/CDKOpenshiftUtility.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/listeners/MinishiftServiceManagerEnvironmentLoader.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/listeners/ServiceManagerEnvironmentLoader.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/ICommonAttributes.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/OpenShiftServerUtils.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/RSync.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/OCBinaryOperation.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/portforwarding/PortForwardingUtils.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/preferences/OCBinary.java
- plugins/org.jboss.tools.openshift.express.client/.classpath
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/handler/AbstractOpenShiftCliHandler.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/handler/PodLogsHandler.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/handler/PortForwardingHandler.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/ServerSettingsWizardPage.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/connection/AdvancedConnectionEditor.java
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR   
new feature
* Are method-/class-/variable-names meaningful?  yes
* Are methods concise, not too long?   yes
* Are catch blocks catching precise Exceptions only (no catch all)?  yes
* Are there unit-tests?  no
* Are there integration tests (or at least a jira to tackle these)?  no
* Is the non-happy path working, too?  not sure, needs testing. 
* Are other parts that use the same component still working fine? seems to be,.... but needs testing
* Does it work?   not 100% sure ;) SEEMS to work, but... might need someone to make sure I didn't break anything.
> JBIDE-24236 - allow per-connection oc overrides

- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/MinishiftPoller.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/controllers/CDK3LaunchController.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/controllers/CDK3ShutdownController.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/ui/internal/AbstractLocationSection.java
- plugins/org.jboss.tools.openshift.common.core/src/org/jboss/tools/openshift/common/core/connection/HostCertificate.java
- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/utils/HttpsPrefixingAdapter.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/OpenshiftJMXConnectionProvider.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/PodDeploymentPathProvider.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/preferences/OCBinary.java
- plugins/org.jboss.tools.openshift.express.ui/src/org/jboss/tools/openshift/express/internal/ui/wizard/application/details/ApplicationDetailsContentProvider.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/ServerSettingsWizard.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/core/server/OpenShiftDebugUtilsTest.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/core/server/OpenShiftServerUtilsPowerMockTest.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/internal/core/WatchManagerTest.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/wizard/newapp/NewApplicationWizardModelTest.java
Signed-off-by: Aurélien Pupier <apupier@redhat.com>
No
> Remove unused import

- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/listeners/ConfigureDependentFrameworksListener.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/connection/AdvancedConnectionEditor.java
> [JBIDE-24775] dont classcast when creating new v3 connection

- plugins/org.jboss.tools.openshift.client/.classpath
- plugins/org.jboss.tools.openshift.client/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.client/pom.xml
> [JBIDE-24745] switch to rest client 5.9.0.Final

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/DeployImageWizardModel.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/DockerConfigMetaData.java
> [JBIDE-24501] dont NPE if pushing img that could not be looked up

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/DeployImageWizardModel.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/wizard/deployimage/DeployImageWizardModelTest.java
> [JBIDE-24499] make sure we load resources if we didn't yet

- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/utils/DialogAdvancedPart.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/connection/AdvancedConnectionEditor.java
> [JBIDE-24790] corrected layout in advanced section of connwizard

- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/controllers/AbstractCDKLaunchController.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/controllers/CDK3LaunchController.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/ui/internal/MinishiftLocationSection.java
- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/explorer/OpenShiftExplorerView.java
> JBIDE-22810 - openshift explorer sometimes shows up empty on windows

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/util/ResourceUtils.java
> [JBIDE-24872] dont NPE if resource is null (looking for bc)

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/OpenShiftServerUtils.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/behavior/OpenShiftLaunchController.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/server/debug/DebugContext.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/server/debug/IDebugListener.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/server/debug/OpenShiftDebugMode.java
- plugins/org.jboss.tools.openshift.js/src/org/jboss/tools/openshift/js/server/behaviour/OpenShiftNodejsLaunchController.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/ServerResourceViewModel.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/core/server/debug/OpenShiftDebugModeTest.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/core/server/util/OpenShiftServerTestUtils.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/util/ResourceMocks.java
> [JBIDE-24869] removed statics in OpenShiftDebugMode for better testability

- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/CDK3Server.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/CDKServer.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/ui/internal/AbstractLocationSection.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/ui/internal/CDK2LocationSection.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/ui/internal/MinishiftLocationSection.java
> JBIDE-24874 - clear up cdk editor browse file vs folder

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/server/debug/OpenShiftDebugMode.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/core/server/debug/OpenShiftDebugModeTest.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/util/ResourceMocks.java
> [JBIDE-24869] replace existing debug port with new requested port

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/DockerImageLabels.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/OpenShiftServerUtils.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/behavior/OpenShiftLaunchController.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/util/ResourceUtils.java
- tests/org.jboss.tools.openshift.test/resources/imageStreamTag_nodejs_latest.json
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/core/server/DockerImageLabelsTest.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/core/server/debug/OpenShiftDebugModeTest.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/core/util/ResourceUtilsTest.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/util/ResourceMocks.java
> [JBIDE-24876] fixed wait for dc

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/connection/AdvancedConnectionEditor.java
> JBIDE-24802 - verifying oc location too aggressively

- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/detection/CDK3RuntimeDetector.java
> JBIDE-24877 - cdk3 detector not careful enough

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/connection/AdvancedConnectionEditor.java
> Jbide 24802 v2

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/OpenShiftCoreMessages.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/OpenShiftCoreMessages.properties
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/preferences/OCBinary.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/OpenShiftUIMessages.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/OpenShiftUIMessages.properties
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/ServerSettingsWizardPage.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/ServerSettingsWizardPageModel.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/importapp/ImportApplicationWizard.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/importapp/ImportJob.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/importapp/ImportProjectOperation.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/newapp/NewApplicationWizard.java
> jbide-24781: Create OpenShift server adapters automatically when creating application

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/newapp/ApplicationSourceDetailViews.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/newapp/ApplicationSourceListPage.java
> [JBIDE-23306] new app wiz: sash form for template list and details

- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/controllers/CDK3LaunchController.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/controllers/CDKLaunchUtility.java
This patch may fix the following JIRAs and should be tested against them:  JBIDE-24676, JBIDE-24188, JBIDE-24293, JBIDE-24222
> JBIDE-24222 - fix xhyve issue for cdk3

- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/controllers/CDK3LaunchController.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/controllers/CDKLaunchController.java
> JBIDE-24935 - small string improvements.

- plugins/org.jboss.tools.openshift.cdk.server/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.cdk.server/plugin.xml
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/CDKCoreActivator.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/listeners/CDKOpenshiftUtility.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/listeners/ConfigureDependentFrameworksListener.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/listeners/ServiceManagerEnvironmentLoader.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/registry/CDKRegistryProvider.java
- plugins/org.jboss.tools.openshift.core/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.core/plugin.xml
- plugins/org.jboss.tools.openshift.core/schema/org.jboss.tools.openshift.core.connection.registryprovider.exsd
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/connection/registry/IConnectionRegistryProvider.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/connection/registry/RegistryProviderModel.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/connection/AdvancedConnectionEditor.java
- tests/org.jboss.tools.openshift.cdk.server.test/src/org/jboss/tools/openshift/cdk/server/test/AllTestsSuite.java
- tests/org.jboss.tools.openshift.cdk.server.test/src/org/jboss/tools/openshift/cdk/server/test/internal/CDKOpenshiftUtilityTest.java
- tests/org.jboss.tools.openshift.cdk.server.test/src/org/jboss/tools/openshift/cdk/server/test/internal/CDKRegistryTest.java
> JBIDE-24491 - allow connection wizard to discover registry url

- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/MinishiftPoller.java
> JBIDE-25068 - working directory does not exist

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/connection/AdvancedConnectionEditor.java
> [JBIDE-25047] correct width of the "Discover" button

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/connection/registry/RegistryProviderModel.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/OpenShiftServerUtils.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/adapter/IOpenshiftServerAdapterProfileDetector.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/behavior/eap/OpenShiftEapModulesController.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/WatchManager.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/util/ResourceUtils.java
> Osfuse 548 clean code during investigation

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/preferences/OCBinary.java
> JBIDE-24990 - oc binary version warning showing when it shouldn't

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/preferences/OCBinaryVersionValidator.java
> JBIDE-25089 - replace illegal dots in qualifier with underscore

- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/listeners/CDKOpenshiftUtility.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/listeners/ServiceManagerEnvironmentLoader.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/registry/CDKRegistryProvider.java
- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/connection/ConnectionWizardPageModel.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/connection/registry/IConnectionRegistryProvider.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/connection/registry/RegistryProviderModel.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/connection/AdvancedConnectionEditor.java
- tests/org.jboss.tools.openshift.cdk.server.test/src/org/jboss/tools/openshift/cdk/server/test/internal/CDKRegistryTest.java
> JBIDE-25049 JBIDE-25046 - fixes to discovering registry url

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/OpenShiftServerEditorModel.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/ServerSettingsWizardPageModel.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/core/server/util/OpenShiftServerTestUtils.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/server/ServerSettingsWizardPageModelTest.java
> use user values for devmode-key, debugport-key & -value

- itests/org.jboss.tools.openshift.ui.bot.test/.classpath
- itests/org.jboss.tools.openshift.ui.bot.test/.gitignore
- itests/org.jboss.tools.openshift.ui.bot.test/build.properties
> Fix bot test compilation in eclipse

- plugins/org.jboss.tools.openshift.cdk.server/plugin.properties
- plugins/org.jboss.tools.openshift.cdk.server/plugin.xml
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/MinishiftBinaryUtility.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/CDK32Poller.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/CDK32Server.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/CDKServer.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/MinishiftPoller.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/controllers/AbstractCDKLaunchController.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/controllers/AbstractCDKShutdownController.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/controllers/CDK3LaunchController.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/controllers/CDK3ShutdownController.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/controllers/CDKLaunchController.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/controllers/CDKShutdownController.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/detection/AbstractCDKRuntimeDetector.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/detection/CDK32RuntimeDetector.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/detection/CDK3RuntimeDetector.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/detection/MinishiftVersionLoader.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/listeners/ConfigureDependentFrameworksListener.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/listeners/MinishiftServiceManagerEnvironmentLoader.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/listeners/ServiceManagerEnvironmentLoader.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/listeners/VagrantServiceManagerEnvironmentLoader.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/ui/internal/CDK32LocationSection.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/ui/internal/CDK32ServerWizardFragment.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/ui/internal/CDK3ServerWizardFragment.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/ui/internal/CDKServerWizardFragment.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/ui/internal/MinishiftLocationSection.java
- tests/org.jboss.tools.openshift.cdk.server.test/src/org/jboss/tools/openshift/cdk/server/test/internal/CDKRegistryTest.java
This PR is for testing purposes. It is not 100% Complete. 
I am not 100% confident in it's implementation but need feedback.
> JBIDE-25055 - initial impl for cdk 3.2 support

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/OpenShiftServerUtils.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/core/connection/ConnectionTest.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/core/server/OpenShiftServerUtilsTest.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/core/server/util/OpenShiftServerTestUtils.java
Signed-off-by:  Andre Dietisheim <adietish@redhat.com>
> [JBIDE-25162] fixed unfinished test-assertions and null conn in server

- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/ui/internal/CDK3ServerWizardFragment.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/ui/internal/CDKServerWizardFragment.java
> JBIDE-25156 - validation error in cdk3.2 wizard

- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/controllers/CDK3LaunchController.java
~~THIS PATCH MAY NOT BE 100%. NEEDS FURTHER TESTING.~~  Patch fixed, works now
> JBIDE-25171 - make sure profile arg is overridden for cdk3.2 adapter

- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/detailviews/AbstractStackedDetailViews.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/ServerSettingsWizardPage.java
> [JBIDE-25143] fix layout and rendering artifacts in server wizard page

- plugins/pom.xml
- pom.xml
- site/pom.xml
- tests/pom.xml
after spending lots of time i didn't manage to configure the coverage correctly. However this PR must fix the duplication index error during the sonar build part. Please, merge this, so that we can ask sonar team for help. (or jbosstools-fuse team - seems the same changes are working for them)
> jbide-24903: configure sonar test coverage

- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/AbstractBotTests.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/OpenShift3BotTests.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/OpenShift3SmokeBotTests.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/OpenShift3StableBotTests.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/adapter/DebuggingEAPAppTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/adapter/ImportApplicationBase.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/create/CreateApplicationFromTemplateTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/common/OpenShiftUtils.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/utils/TestUtils.java
Stabilization of LinkToCreateNewProjectTest and other minor fixes in tests
> JBIDE-25198 Stabilization of LinkToCreateNewProjectTest and minor tests fixes

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/OpenShiftUIMessages.properties
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/handler/EditResourceLimitsPage.java
> [JBIDE-25092] correct resource limit labels and vert widget pos

- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/OpenShift3StableBotTests.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/adapter/ImportApplicationBase.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/adapter/ImportApplicationWizardTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/common/OpenShiftUtils.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/project/ProjectPropertiesTest.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/wizard/importapp/ImportApplicationWizard.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/wizard/server/ServerSettingsWizard.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/wizard/server/ServerSettingsWizardPage.java
> JBIDE-25210 ImportApplicationWizardTest stabilization fixes

- plugins/org.jboss.tools.openshift.io.ui/src/main/java/org/jboss/tools/openshift/io/internal/ui/DefaultLoginProvider.java
> [JBIDE-25169] - Deadlock when tokenProvider is invoked during start

- itests/org.jboss.tools.openshift.ui.bot.test/README.md
- itests/org.jboss.tools.openshift.ui.bot.test/pom.xml
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/OpenShift3StableBotTests.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/integration/docker/DeployDockerImageTest.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/condition/BrowserContainsText.java
> JBIDE-25211 DeployDockerImageTest stabilization fixes

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/newapp/fromimage/ApplicationSourceFromImageModel.java
> jbide-24778: use git repo URL of eclipse project when creating app

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/OpenshiftJMXConnectionProvider.java
read port from Server Adapter Connection URL instead of using an
hardcoded one. It is also taking care when no port is specified (such as
open.paas.redhat.com and surely most of publicly available instances)
I don't know how to unit test it as there are several static methods and tests are not in the same package (no fragment used). Suggestions?
> JBIDE-24438 - Read port from Connection URL

- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/databinding/FormEditorPresenter.java
- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/utils/DataBindingUtils.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/OpenShiftServerEditorModel.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/OpenShiftServerEditorSection.java
> [JBIDE-25115] server editor: warn "restart to activate changes"

- plugins/org.jboss.tools.openshift.js/.project
> openshift.js is missing a .project file

- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/adapter/ImportApplicationWizardTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/common/OpenShiftUtils.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/condition/OpenShiftResourceExists.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/view/resources/OpenShiftProject.java
> JBIDE-25379 Fix ImportApplicationWizardTest

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/handler/DeleteResourceHandler.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/internal/ui/handler/DeleteResourceHandlerTest.java
> jbide-24972: DeleteResourceHandlerTest is failing for Windows

- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/advanced/EditResourceLimitsTest.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/requirement/OpenShiftResources.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/utils/OpenShiftLabel.java
> [JBIDE-25090] - Create IT tests for memory tuning

- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/OpenShift3StableBotTests.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/adapter/ImportApplicationBase.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/adapter/ImportApplicationWizardGitTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/adapter/ImportApplicationWizardTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/advanced/CreateResourcesTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/advanced/EditResourcesTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/basic/LabelsTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/basic/NewApplicationWizardHandlingTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/basic/TemplateParametersTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/create/CreateApplicationOnBuilderImageTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/connection/v3/ConnectionPropertiesTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/connection/v3/ConnectionWizardHandlingTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/connection/v3/RemoveConnectionTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/integration/docker/DeployDockerImageTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/project/CreateNewProjectTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/project/DeleteProjectTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/project/LinkToCreateNewProjectTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/project/ProjectNameValidationTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/project/ProjectPropertiesTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/project/ResourcesTest.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/condition/CentralIsLoaded.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/requirement/CleanOpenShiftConnectionRequirement.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/utils/OpenShiftLabel.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/view/resources/OpenShiftProject.java
> JBIDE-25212 JBIDE-25277 CreateResourcesTest and ImportApplicationWizardGitTest Tests Stabilization

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/OpenShiftServerEditorSection.java
> JBIDE-25380

- plugins/org.jboss.tools.openshift.client/.classpath
- plugins/org.jboss.tools.openshift.client/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.client/pom.xml
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/OpenShiftAPIAnnotations.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/OpenShiftServerUtils.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/server/debug/DebugContext.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/server/debug/EnvironmentVariables.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/server/debug/LivenessProbe.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/server/debug/OpenShiftDebugMode.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/server/debug/RouteTimeout.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/util/ResourceUtils.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/core/server/OpenShiftServerUtilsTest.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/core/server/debug/OpenShiftDebugModeTest.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/core/server/util/OpenShiftServerTestUtils.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/core/util/ResourceUtilsTest.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/util/ResourceMocks.java
> [JBIDE-24868] debugging: increase (route) timeout, disable probe

- plugins/org.jboss.tools.openshift.client/.classpath
- plugins/org.jboss.tools.openshift.client/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.client/pom.xml
> [JBIDE-25389] using latest openshift-restclient-java 5.9.3.Final

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/preferences/OCBinary.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/ServerSettingsWizardPage.java
> JBIDE-25256 - fix binary status in OS server wizard 

- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/OpenShift3BotTests.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/OpenShift3StableBotTests.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/advanced/EditResourceLimitsTest.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/condition/BrowserContainsText.java
Added quite a big timeout because of slaves speed.
> JBIDE-25281 EditResourceLimitsTest added in suites

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/OpenshiftJMXConnectionProvider.java
In order to test, update your EAP deployment and add the following env variable:
* AB_JOLOKIA_PORT with a value different from 8778
then start your server adapter and try browsing the JMX connection
Signed-off-by:** Jeff MAURY <jmaury@redhat.com>
> [JBIDE-25291] - Read Jolokia port from image configuration instead of hardcoded to default value

- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/OpenShift3StableBotTests.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/connection/v3/StoreConnectionTest.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/utils/SecureStorage.java
> JBIDE-25197 StoreConnectionTest fix

- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/advanced/CreateResourcesTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/integration/docker/DeployDockerImageTest.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/condition/BrowserContainsText.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/condition/PageIsLoaded.java
> Stabilization fixes for DeployDockerImageTest and CreateResourcesTest

- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/CDK32Server.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/CDK3Server.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/detection/CDK32RuntimeDetector.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/detection/CDK3RuntimeDetector.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/ui/internal/CDK32LocationSection.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/ui/internal/CDK32ServerWizardFragment.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/ui/internal/CDK3ServerWizardFragment.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/ui/internal/MinishiftLocationSection.java
> JBIDE-25149 - code cleanup

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/OpenShiftServerEditorSection.java
> [JBIDE-25452] checking correct server value for devmode

- plugins/org.jboss.tools.openshift.client/.classpath
- plugins/org.jboss.tools.openshift.client/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.client/pom.xml
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/server/debug/OpenShiftDebugMode.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/core/server/debug/OpenShiftDebugModeTest.java
> [JBIDE-25510] use openshift-restclient-5.9.4-SNAPSHOT with fix

- plugins/org.jboss.tools.openshift.client/.classpath
- plugins/org.jboss.tools.openshift.client/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.client/pom.xml
> [JBIDE-25512] using openshift-restclient-java 5.9.4.Final

- plugins/org.jboss.tools.openshift.ui/.classpath
- plugins/org.jboss.tools.openshift.ui/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.ui/pom.xml
- Switch commons-validator to 1.6
> [JBDS-4631] - First analysis and actions for CVE vulnerabilities

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/job/CreateResourceJob.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/common/AbstractProjectPage.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/connection/AdvancedConnectionEditor.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/resource/ResourcePayloadPage.java
> [JBIDE-25166] - Resource wizard: using (formally valid) URL to non-existing/erroneous json does not show error message

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/connection/AdvancedConnectionEditor.java
> Fix broken openshift build due to formatting

- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/SelectProjectComponentBuilder.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/newapp/ApplicationSourceListPage.java
> [JBIDE-25610] fix button alignement in new app wizard

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/preferences/OCBinary.java
> JBIDE-25603 - IOException when validating oc version

- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/condition/BrowserContainsText.java
[Related jira](https://issues.jboss.org/browse/JBIDE-25680)
Signed-off-by: vprusa <vprusa@redhat.com>
feature for f8 analytics itests
Added disabling page refresh
Overloading constructor and method parameters
Tested locally for f8analztics login using jboss developer account
Described in jira mentioned above
> Added BrowserContainsText refresh skip

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/connection/registry/RegistryProviderModel.java
> JBIDE-25602 - fix NPE

- plugins/org.jboss.tools.openshift.cdk.server/plugin.properties
- plugins/org.jboss.tools.openshift.cdk.server/plugin.xml
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/CDK32Server.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/CDKServer.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/Minishift17Server.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/listeners/ConfigureDependentFrameworksListener.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/listeners/ServiceManagerEnvironmentLoader.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/ui/internal/CDK32LocationSection.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/ui/internal/CDK32ServerWizardFragment.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/ui/internal/CDK3ServerWizardFragment.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/ui/internal/CDKServerWizardFragment.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/ui/internal/Minishift17LocationSection.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/ui/internal/Minishift17ServerWizardFragment.java
> JBIDE-25295 - server adapter for minishift 1.7+

- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/OpenShift3StableBotTests.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/connection/v3/CreateNewConnectionTest.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/view/OpenShiftExplorerView.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/wizard/v3/BasicAuthenticationSection.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/wizard/v3/OpenShift3ConnectionWizard.java
> JBIDE-25196 CreateNewConnectionTest ITest stabilization

- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/ui/internal/CDK32ServerWizardFragment.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/ui/internal/MinishiftLocationSection.java
> JBIDE-25692 - add minishift home to new cdk wizard

- plugins/org.jboss.tools.openshift.cdk.server/plugin.xml
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/CDKServer.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/MinishiftPoller.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/VagrantPoller.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/controllers/AbstractCDKShutdownController.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/controllers/CDK3LaunchController.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/controllers/CDK3ShutdownController.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/controllers/CDKLaunchController.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/controllers/CDKLaunchUtility.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/controllers/CDKShutdownController.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/listeners/CDKLaunchEnvironmentUtil.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/listeners/MinishiftServiceManagerEnvironmentLoader.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/listeners/VagrantServiceManagerEnvironmentLoader.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/ui/internal/CDK32CredentialSection.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/ui/internal/CDKCredentialSection.java
> JBIDE-25617 - add support for skip-registration flags

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/preferences/OCBinary.java
> JBIDE-25666 - connection-override oc not being used

- plugins/org.jboss.tools.openshift.client/.classpath
- plugins/org.jboss.tools.openshift.client/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.client/pom.xml
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/OpenShiftCoreMessages.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/OpenShiftCoreMessages.properties
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/preferences/OCBinary.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/preferences/OCBinaryVersionValidator.java
> [JBIDE-25734] - Verify space related issues with oc rsync

- features/org.jboss.tools.openshift.cdk.test.feature/feature.xml
> Adding cdk.ui.bot.tests features

- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/listeners/MinishiftServiceManagerEnvironmentLoader.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/listeners/ServiceManagerEnvironment.java
> JBIDE-25701 - ensure minishift default username is correct

- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/controllers/CDK3LaunchController.java
- tests/org.jboss.tools.openshift.cdk.server.test/src/org/jboss/tools/openshift/cdk/server/test/internal/CDK32LaunchControllerTest.java
> JBIDE-25617 - ensure skip registration responds to changes

- plugins/org.jboss.tools.openshift.client/.classpath
- plugins/org.jboss.tools.openshift.client/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.client/pom.xml
> [JBIDE-25751] use latest openshift-restclient-java 5.9.5.Final

- plugins/org.jboss.tools.openshift.common.core/src/org/jboss/tools/openshift/internal/common/core/util/KeyValueFilterFactory.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/util/ResourceUtils.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/resource/DeleteResourcesWizard.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/resource/DeleteResourcesWizardModel.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/core/util/ResourceUtilsIsMatchingLabelsTest.java
> [JBIDE-25755] show resources without labels if filter is empty

- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/ui/internal/CDK32CredentialSection.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/ui/internal/CDKCredentialSection.java
> JBIDE-25759 - improve cdk editor ui

- plugins/org.jboss.tools.openshift.client/.classpath
- plugins/org.jboss.tools.openshift.client/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.client/pom.xml
> [JBIDE-25506] fixes .git exclusion filter when rsync'ing

- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/detection/CDK3RuntimeDetector.java
> JBIDE-25772 - log which file failed to parse (minishift config.json)

- plugins/org.jboss.tools.openshift.common.core/src/org/jboss/tools/openshift/internal/common/core/preferences/AbstractPreferenceValue.java
- plugins/org.jboss.tools.openshift.common.core/src/org/jboss/tools/openshift/internal/common/core/preferences/StringPreferenceValue.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/preferences/OpenShiftCorePreferences.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/connection/AdvancedConnectionEditor.java
> JBIDE-25549 - fix for invalid oc location when using system path

- plugins/org.jboss.tools.openshift.client/.classpath
- plugins/org.jboss.tools.openshift.client/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.client/pom.xml
> [JBIDE-25823] using openshift-restclient-java 6.0.0.Final

- plugins/org.jboss.tools.openshift.cdk.server/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.cdk.server/resources/whitelistGenerator.sh
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/CDKServer.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/detection/UnifiedMinishiftRuntimeDetector.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/ui/internal/CDK3ServerWizardFragment.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/ui/internal/view/CDKActionProvider.java
THIS PR REQUIRES JBIDE-25753
DO NOT COMMIT THIS UNTIL JBIDE-25753 IS PUSHED TO MASTER
> JBIDE-25822 - be able to run minishift setup-cdk for a cdk server 

- plugins/org.jboss.tools.openshift.common.core/src/org/jboss/tools/openshift/common/core/connection/ConnectionsRegistry.java
> jbide-25590: connection is not refreshed if you modify its url

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/ICommonAttributes.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/property/ConnectionPropertySource.java
> [JBIDE-25668] - Properties view displays a strange label for OpenShift3 connections

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/newapp/NewApplicationWizardModel.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/wizard/newapp/NewApplicationWizardModelTest.java
> jbide-25581: missing labels when creating an app from a builder image

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/explorer/OpenShiftExplorerContentProvider.java
> [JBIDE-25681] - OpenShift view: Show pods/deployments for apps without service

- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/detection/UnifiedMinishiftRuntimeDetector.java
> JBIDE-25873 - fixing runtime detection labels for cdk / ms

- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/wizard/KeyValueWizardPage.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/common/ResourceLabelsPage.java
>  [JBIDE-22245] keyvaluewiz: corrected all "Label"->"Key"

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/behavior/OpenShiftPublishController.java
> [JBIDE-25855] use now public StandardFileSystemPublishController

- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/ui/internal/CDK3ServerWizardFragment.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/ui/internal/Minishift17ServerWizardFragment.java
> JBIDE-25859 - minishift bin after dl not filled in, bin not executable

- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/advanced/CreateResourcesTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/basic/LabelsTest.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/utils/OpenShiftLabel.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/wizard/page/ResourceLabelsWizardPage.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/wizard/v3/TemplatesCreator.java
> JBIDE-25898 OpenShift ITests fixes for latest changes in code

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/server/debug/DebugContext.java
> [JBIDE-25672] improved err msg for missing debugmode arguments

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/job/DeleteResourcesJob.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/resource/DeleteResourcesWizardModel.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/internal/core/WatchManagerTest.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/internal/core/job/DeleteResourcesJobTest.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/internal/ui/handler/DeleteResourceHandlerTest.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/util/ResourceMocks.java
> [JBIDE-25670] remove all resources in a fixed order

- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/CDK3Server.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/ui/internal/CDK32ServerWizardFragment.java
> Change default minishift_home in new cdk / ms server fragment

- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/ui/internal/CDK32ServerWizardFragment.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/ui/internal/CDKServerWizardFragment.java
> JBIDE-25834

- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/ui/internal/view/SetupCDKJob.java
> JBIDE-25914 - bug after poorly tested sonar changes

- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/detection/MinishiftDownloadRuntimesProvider.java
> JBIDE-25917 - read from web yaml first if possible

- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/CDKAbstractTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/CDKAllTestsSuite.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/CDK32ServerAdapterProfilesTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/CDKServerAdapterAbstractTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/CDKServerAdapterSetupCDKTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/editor/CDK32ServerEditorTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/editor/CDK3ServerEditorTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/editor/CDKServerEditorAbstractTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/editor/MinishiftServerEditorTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/editor/launch/CDKLaunchConfigurationTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/CDKServerWizardAbstractTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/utils/CDKTestUtils.java
- test-framework/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/core/label/CDKLabel.java
- test-framework/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/server/ui/CDKServer.java
> JBIDE-25869 - Integration tests for setup-cdk server adapter context menu item

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/docker/DockerConfigMetaData.java
- tests/org.jboss.tools.openshift.cdk.server.test/src/org/jboss/tools/openshift/cdk/server/test/internal/CDKLaunchControllerTest.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/wizard/deployimage/DockerConfigMetaDataTest.java
> Fix OpenShift tests failures due to Photon

- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/explorer/DefaultPropertySection.java
- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/explorer/DefaultPropertySheetPage.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/property/ResourcePropertySource.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/property/tabbed/OpenShiftResourcePropertySection.java
> [JBIDE-25825] - Properties: Basic block should always be displayed 1st

- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/ui/internal/CDK32ServerWizardFragment.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/ui/internal/CDK3ServerWizardFragment.java
> JBIDE-25971 - add registration link to CDK wizard

- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/utils/StyledTextUtils.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/newapp/ApplicationSourceDetailViews.java
> [JBIDE-25900] - Support hyperlinks in Project Template Details group

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/property/ConnectionPropertySource.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/property/ConnectionPropertySourceTest.java
> [JBIDE-25967] - Properties view: Add OC version for OpenShift connection

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/job/DeployImageJob.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/DeployImageWizardModel.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/IServiceAndRoutingPageModel.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/PodPortValidator.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/ServicePortAdapter.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/ServicePortDialog.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/ServicesAndRoutingPage.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/validator/PodPortValidatorTest.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/wizard/deployimage/DeployImageWizardModelTest.java
> [JBIDE-25905] route page: reuse existing table item instances

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/connection/Connection.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/handler/NewProjectHandler.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/newapp/ApplicationSourceTreeItems.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/server/ServerResourceViewModelWithDeploymentConfigTest.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/server/ServerResourceViewModelWithReplicationControllerTest.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/server/ServerResourceViewModelWithServiceTest.java
> jbide-25756: fix: connection displays project that was deleted

- plugins/org.jboss.tools.openshift.ui/plugin.xml
> [JBIDE-26078] override edit resource cmd label in properties view

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/OpenShiftUIMessages.properties
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/project/ManageProjectsWizardPage.java
> [JBIDE-26073] corrected message to confirm project removal

- itests/org.jboss.tools.openshift.ui.bot.test/resources/oclinks.properties
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/OpenShift3BotTests.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/OpenShift3StableBotTests.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/advanced/EditResourceLimitsTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/common/OCBinaryLocationTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/connection/v3/SetOCForNewConnectionTest.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/requirement/OpenShiftCommandLineToolsRequirement.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/wizard/v3/OpenShift3ConnectionWizard.java
> JBIDE-24933 OC setting for connection ITest

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/handler/ScaleDeploymentHandler.java
> jbide-24979: Scale up/down/to: NPE if you have only rc, no dc

- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/OpenShift3StableBotTests.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/advanced/EditResourcesTest.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/utils/OpenShiftLabel.java
> JBIDE-25209 EditResources test stabilization

- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/OpenShift3StableBotTests.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/advanced/LogsTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/create/CreateApplicationFromTemplateTest.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/utils/OpenShiftLabel.java
> JBIDE-25208 LogsTest ITests stabilization

- tests/org.jboss.tools.openshift.egit.test/src/org/jboss/tools/openshift/egit/internal/test/util/TestRepository.java
* corrected deprecated repository#getRef -> repository#findRef
* added auto-closing try(resource) to non-closed resources
> [JBIDE-26139] corrected deprecated repo#getRef -> repo#findRef

- plugins/org.jboss.tools.openshift.ui/plugin.xml
This depends on https://github.com/jbosstools/jbosstools-openshift/pull/1759 to be merged first, so that openshift compiles again.
> [JBIDE-25546] explorer: ctx menu "Delete", "Delete Resources" visible only if items selected

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/handler/EditConnectionHandler.java
> jbide-25838: Explorer: expand connection to the level that it was

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/job/DeleteResourcesJob.java
> [JBIDE-26171] delete resources: ensure ordering of resources is constant

- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/databinding/DisableableMultiValitdator.java
> [JBIDE-26224] - Fix compilation error due to 4.9 TP

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/DeployImagePage.java
> [JBIDE-26226] fixed comp err caused by change in ObjectToStringConverter

- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/OpenShift3StableBotTests.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/advanced/ScalingTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/basic/OpenNewApplicationWizardWithNoProjectTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/create/CreateApplicationOnBuilderImageTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/common/OCBinaryLocationTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/common/OpenShiftUtils.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/connection/v3/OpenNewConnectionWizardTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/connection/v3/SetOCForNewConnectionTest.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/utils/OpenShiftLabel.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/view/OpenShiftExplorerView.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/view/resources/ServerAdapter.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/wizard/AbstractOpenShiftApplicationWizard.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/wizard/v3/NewOpenShift3ApplicationWizard.java
> JBIDE 25201 - Fix for CreateApplicationOnBuilderImageTest

- tests/org.jboss.tools.openshift.test/META-INF/MANIFEST.MF
- tests/org.jboss.tools.openshift.test/projects/SpringBootProject/.classpath
- tests/org.jboss.tools.openshift.test/projects/SpringBootProject/.project
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/core/server/behavior/springboot/OpenShiftSpringBootProfileDetectorTest.java
> JBIDE-25592: Tests: fix OpenShiftSpringBootProfileDetectorTest

- plugins/org.jboss.tools.openshift.client/.classpath
- plugins/org.jboss.tools.openshift.client/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.client/pom.xml
> [JBIDE-26251] use client lib that won't "-p" when port forwarding

- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/SelectProjectComponentBuilder.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/common/AbstractProjectPage.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/newapp/ApplicationSourceListPage.java
> JBIDE-26179 add "Refresh..." button in New OpenShift Application wizard

- itests/org.jboss.tools.openshift.ui.bot.test/launchers/OpenShift3BotTests OAuth.launch
- itests/org.jboss.tools.openshift.ui.bot.test/launchers/OpenShift3BotTests.launch
- itests/org.jboss.tools.openshift.ui.bot.test/launchers/OpenShift3StableBotTests OAuth.launch
- itests/org.jboss.tools.openshift.ui.bot.test/launchers/OpenShift3StableBotTests.launch
- itests/org.jboss.tools.openshift.ui.bot.test/pom.xml
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/OpenShift3StableBotTests.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/adapter/CreateServerAdapterTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/adapter/PublishChangesTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/advanced/PortForwardingTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/basic/NewApplicationWizardHandlingTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/create/CreateApplicationFromTemplateTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/connection/v3/StoreConnectionTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/integration/docker/AbstractDockerImageTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/project/ProjectNameValidationTest.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/requirement/OpenShiftResources.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/utils/OpenShiftLabel.java
> JBIDE-25207 PortForwardingTest ITest stabilization

- plugins/org.jboss.tools.openshift.cdk.server/plugin.xml
Added missing packages renaming in plugin.xml corresponding to changes made in JBIDE-26164
> JBIDE-26308 Update classes fully qualified names in plugin.xml

- plugins/org.jboss.tools.openshift.io.ui/plugin.xml
> JBIDE-26309 Fixing correct class for DefaultLoginProvider in plugin.xml

- itests/org.jboss.tools.openshift.ui.bot.test/pom.xml
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/OpenShift3StableBotTests.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/advanced/OSExplorerResourceTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/advanced/ScalingTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/integration/docker/AbstractDockerImageTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/integration/docker/DeployDockerImageTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/integration/docker/DeployVariousDockerImagesTest.java
- test-framework/org.jboss.tools.openshift.reddeer/META-INF/MANIFEST.MF
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/requirement/OpenShiftResources.java
> JBIDE-26298 JBIDE-25205 JBIDE25206 OpenShift ITests stabilization

- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/OpenShift3StableBotTests.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/advanced/DeleteResourceTest.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/condition/AmountOfResourcesExists.java
to stable suite
JBIDE-25204 DeleteResourceTest OpenShift ITests stabilization
> JBIDE-25203 Stabilization of DeploymentTests ITest and adding this test

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/behavior/OpenShiftLaunchController.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/behavior/OpenShiftShutdownController.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/util/MavenCharacter.java
> [JBIDE-26327] dont NPE on adapter shutdown if project was deleted

- plugins/org.jboss.tools.openshift.client/.classpath
- plugins/org.jboss.tools.openshift.client/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.client/pom.xml
> [JBIDE-26333] use fixed openshift-restclient-java 6.1.2.Final

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/job/OpenShiftJobs.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/portforwarding/PortForwardingUtils.java
> jbide-26159: Server adapter: port forwarding isn't stopped if you delete a pod

- plugins/org.jboss.tools.openshift.client/pom.xml
> Switch to latest commons compress to fix security issue reported by snyk.io

- itests/org.jboss.tools.openshift.ui.bot.test/resources/eap71-basic-s2i-helloworld.json
- itests/org.jboss.tools.openshift.ui.bot.test/resources/os3projectWithResources/eap71-basic-s2i-helloworld.json
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/OpenShift3StableBotTests.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/adapter/CreateServerAdapterTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/adapter/PublishChangesTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/adapter/ServerAdapterWizardHandlingTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/advanced/DeleteResourceTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/advanced/EditResourcesTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/advanced/ImportApplicationTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/advanced/InteligentDeleteResourceTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/advanced/PortForwardingTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/advanced/TriggerBuildTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/basic/TemplateParametersTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/create/CreateApplicationFromTemplateTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/create/DeploymentTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/debug/DebuggingEAPAppTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/integration/docker/AbstractDockerImageTest.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/requirement/OpenShiftResources.java
> JBIDE-26375 Template update for EAP71 in ITests

- plugins/org.jboss.tools.openshift.client/.classpath
- plugins/org.jboss.tools.openshift.client/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.client/pom.xml
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/webhooks/WebHooksComponent.java
> [JBIDE-26411] use latest openshift-restclient-java 7.0.0

- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/internal/cdk/server/core/adapter/CDK3Server.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/internal/cdk/server/core/listeners/CDKOpenshiftUtility.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/internal/cdk/server/core/listeners/CDKServerUtility.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/internal/cdk/server/core/listeners/ConfigureDependentFrameworksListener.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/internal/cdk/server/ui/CDK32ServerWizardFragment.java
- tests/org.jboss.tools.openshift.cdk.server.test/src/org/jboss/tools/openshift/internal/cdk/server/test/CDKOpenshiftUtilityTest.java
- tests/org.jboss.tools.openshift.cdk.server.test/src/org/jboss/tools/openshift/internal/cdk/server/test/CDKRegistryTest.java
> [JBIDE-25830] try find oc in minishift home

- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/OpenShift3StableBotTests.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/adapter/ImportApplicationBase.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/adapter/ImportApplicationWizardGitTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/advanced/HandleCustomTemplateTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/advanced/ImportApplicationTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/create/CreateApplicationFromTemplateTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/integration/openshift/io/GetOpenShiftIOTokenTest.java
JBIDE-26318 ImportApplicationTest OpenShift ITest Stabilization
> JBIDE-26319 HandleCustomTemplate OpenShift ITests stabilization

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/ServicePortAdapter.java
> [JBIDE-26447] add support for nodePort in ServicePortAdapter

- itests/org.jboss.tools.openshift.ui.bot.test/pom.xml
- itests/org.jboss.tools.openshift.ui.bot.test/resources/oclinks.properties
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/OpenShift3StableBotTests.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/adapter/CreateServerAdapterTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/advanced/InteligentDeleteResourceTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/advanced/OSExplorerResourceTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/connection/v3/SetOCForNewConnectionTest.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/view/resources/AbstractOpenShiftExplorerItem.java
> JBIDE-26443 Update oc in ITests to 3.11

- itests/org.jboss.tools.openshift.ui.bot.test/pom.xml
- itests/org.jboss.tools.openshift.ui.bot.test/resources/eap-cd-basic-s2i-helloworld.json
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/OpenShift3EAPCDTests.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/adapter/PublishChangesEAPCDTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/advanced/ImportApplicationEAPCDTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/debug/DebuggingEAPAppEAPCDTest.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/requirement/OpenShiftResources.java
> JBIDE-26442 Automation of EAP-CD ITests for OpenShift

- plugins/org.jboss.tools.openshift.common.core/META-INF/MANIFEST.MF
> JBIDE-26470 - Fix Java11+ compilation error

- plugins/org.jboss.tools.openshift.client/.classpath
- plugins/org.jboss.tools.openshift.client/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.client/pom.xml
> [JBIDE-26446] use openshift-restclient-java 7.0.0.Final

- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/CDK32IntegrationTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/CDK32ServerAdapterProfilesTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/CDKServerAdapterSetupCDKTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/CDKWrongCredentialsTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/MinishiftServerAdapterProfilesTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/MinishiftServerAdapterTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/openshift/CDKImageRegistryUrlAbstractTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/openshift/CDKImageRegistryUrlDiscoveryFailureTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/openshift/CDKImageRegistryUrlDiscoveryTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/openshift/CDKImageRegistryUrlValidatorTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/editor/CDK32ServerEditorTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/editor/MinishiftServerEditorTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/editor/launch/CDKLaunchConfigurationTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/runtime/CDK32RuntimeDetectionTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/runtime/CDK3RuntimeDetectionTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/CDK32ServerWizardTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/download/CDK32DownloadRuntimeTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/download/DownloadContainerRuntimeDefaultSettingsTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/download/DownloadLatestContainerRuntimeTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/download/DownloadRuntimesWizardTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/download/MinishiftDownloadRuntimeTest.java
- test-framework/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/core/enums/CDKVersion.java
- test-framework/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/requirements/DisableSecureStorageRequirement.java
> Implement fixes for upstream changes, upversioning cdk/minishift versions

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/newapp/ApplicationSourceListPage.java
> JBIDE-24492 Custom template info is loaded after path changed in

- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/OpenShift3StableBotTests.java
> JBIDE-26320 Add ScallingTest in stable suite

- plugins/org.jboss.tools.openshift.egit.core/src/org/jboss/tools/openshift/egit/core/EGitUtils.java
> corrected EGitUtils#checkoutBranch to compile with EGit 5.2.0

- plugins/org.jboss.tools.openshift.client/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.client/pom.xml
- plugins/org.jboss.tools.openshift.common.core/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.common.core/src/org/jboss/tools/openshift/common/core/utils/UrlUtils.java
>  [JBIDE-26460] replaced javax.xml.bind.DatatypeConverter by jdk8 means

- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/advanced/EditResourcesTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/basic/TemplateParametersTest.java
> JBIDE-24867 Remove OpenShift ITests dependencies on private repos

- plugins/org.jboss.tools.openshift.common.ui/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/connection/ConnectionEditorsStackedView.java
- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/connection/ConnectionWizardPage.java
- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/utils/OCCommandUtils.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/common/ui/utils/OCCommandUtilsTest.java
ConnectionWizard, add relevant test classes
> JBIDE-26117 Add "Parse login command from clipboard" button in

- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/connection/v3/ConnectionWizardHandlingTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/connection/v3/CreateNewConnectionTest.java
- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/connection/ConnectionWizardPage.java
- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/connection/ConnectionWizardPageModel.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/utils/OpenShiftLabel.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/utils/SecureStorage.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/wizard/v3/OpenShift3ConnectionWizard.java
> JBIDE-26501 Remove Default Server and Server Type from OpenShift

- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/utils/OCCommandUtils.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/common/ui/utils/OCCommandUtilsTest.java
> JBIDE-26530 OCCommandUtils fixes for different formats of oc login

- plugins/org.jboss.tools.openshift.io.core/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.io.core/pom.xml
- plugins/org.jboss.tools.openshift.io.core/src/main/java/org/jboss/tools/openshift/io/core/OSIOUtils.java
- tests/org.jboss.tools.openshift.io.test/META-INF/MANIFEST.MF
- tests/org.jboss.tools.openshift.io.test/pom.xml
> JBIDE-26540 Update jjwt libraries to 0.10.5

- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/connection/ConnectionWizardPage.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/connection/OAuthDetailView.java
> JBIDE-26532 Fix for update UI when copying login command with different

- plugins/org.jboss.tools.openshift.client/.classpath
- plugins/org.jboss.tools.openshift.client/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.client/build.properties
- plugins/org.jboss.tools.openshift.client/pom.xml
> [JBIDE-26577] use openshift-restclient-java 7.1.0.Final

- plugins/org.jboss.tools.openshift.ui/META-INF/MANIFEST.MF
> JBIDE-26578: org.jboss.tools.openshift.ui fails to load

- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/MinishiftServerAdapterProfilesTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/MinishiftServerAdapterTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/editor/MinishiftServerEditorTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/download/DownloadContainerRuntimeDefaultSettingsTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/download/DownloadLatestContainerRuntimeTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/download/MinishiftDownloadRuntimeTest.java
- test-framework/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/core/enums/CDKVersion.java
> Update downloading artifacts of minishift

- plugins/org.jboss.tools.openshift.core/plugin.xml
> JBIDE-26623 Fix jst.web model 4.0 for OpenShift Server Adapter

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/ChooseOpenshiftConnectionComposite.java
> JBIDE-25814 Select recent connection in server adapter wizard instead of

- itests/org.jboss.tools.openshift.ui.bot.test/META-INF/MANIFEST.MF
- itests/org.jboss.tools.openshift.ui.bot.test/pom.xml
- itests/org.jboss.tools.openshift.ui.bot.test/resources/eap72-basic-s2i-helloworld.json
- itests/org.jboss.tools.openshift.ui.bot.test/resources/os3projectWithResources/eap72-basic-s2i-helloworld.json
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/adapter/PublishChangesTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/advanced/DeleteResourceTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/advanced/EditResourceLimitsTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/advanced/EditResourcesTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/basic/NewApplicationWizardHandlingTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/basic/TemplateParametersTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/create/CreateApplicationFromTemplateTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/common/OpenShiftUtils.java
- test-framework/org.jboss.tools.openshift.reddeer/META-INF/MANIFEST.MF
- test-framework/org.jboss.tools.openshift.reddeer/pom.xml
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/requirement/OpenShiftResources.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/utils/OpenShiftLabel.java
> JBIDE-26575 OpenShift ITests updates and stabilization fixes

- plugins/org.jboss.tools.openshift.client/.classpath
- plugins/org.jboss.tools.openshift.client/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.client/pom.xml
- plugins/org.jboss.tools.openshift.common.ui/.classpath
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/behavior/OpenShiftLaunchController.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/util/ResourceUtils.java
- plugins/org.jboss.tools.openshift.js/.classpath
- plugins/org.jboss.tools.openshift.ui/.classpath
- tests/org.jboss.tools.openshift.cdk.server.test/.classpath
- tests/org.jboss.tools.openshift.egit.test/.classpath
- tests/org.jboss.tools.openshift.test/.classpath
> jbide-26160: Server Adapter stays in [Debugging] when you kill the pod

- plugins/org.jboss.tools.openshift.client/.classpath
- plugins/org.jboss.tools.openshift.client/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.client/pom.xml
> JBIDE-26647: bump openshift client to 8.0.0-SNAPSHOT

- plugins/org.jboss.tools.openshift.client/.classpath
- plugins/org.jboss.tools.openshift.client/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.client/pom.xml
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/job/DeployImageJobTest.java
> JBIDE-26693: bump openshift client to 8.0.0.Final

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/resource/ResourcePayloadPage.java
> [JBIDE-26722] new resource wiz: correct right alignment of source group

- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/utils/UIUtils.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/dialog/ResourceSummaryDialog.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/job/CreateApplicationFromImageJob.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/job/DeployImageJob.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/ResourceDetailViews.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/ServerSettingsWizardPage.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/DeployImageWizard.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/newapp/fromtemplate/NewApplicationSummaryFromTemplateDialog.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/resource/NewResourceWizard.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/internal/test/ui/wizard/newapp/ResourceDetailsLabelProviderTest.java
* shortened imagestream error message
* display message type (warning, info, etc.)
> [JBIDE-24498] improve info display in resource summary dialog

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/OpenShiftDeploymentPage.java
> [JBIDE-26744] trigger full deploy upon saving server in deployment (editor) page

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/OpenShiftServerUtils.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/behavior/OpenShiftPublishController.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/behavior/eap/OpenShiftEapPublishController.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/OpenShiftDeploymentPage.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/core/server/OutputNamesCacheTest.java
> [JBIDE-26754] wildfly: first undeploy and then only redeploying with new name

- plugins/org.jboss.tools.openshift.ui/plugin.xml
> [JBIDE-26797] corrected duplicate id for openshift deployment page

- test-framework/org.jboss.tools.openshift.reddeer/pom.xml
> Chnage version of org.apache.commons from 1.18 to 1.19

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/IDialogProvider.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/preferences/IOpenShiftCorePreferences.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/behavior/JavaDebugPreferences.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/behavior/OpenShiftLaunchController.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/Dialogs.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/dialog/DialogProvider.java
> [JBIDE-26802] warn if "show method result" is turned on

- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/CDKAbstractTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/CDKAllTestsSuite.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/CDK32IntegrationTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/CDK32ServerAdapterProfilesTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/CDKServerAdapterSetupCDKTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/CDKWrongCredentialsTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/openshift/CDKImageRegistryUrlDiscoveryFailureTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/openshift/CDKImageRegistryUrlDiscoveryTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/openshift/CDKImageRegistryUrlValidatorTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/editor/CDK32ServerEditorTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/editor/launch/CDKLaunchConfigurationTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/runtime/CDK32RuntimeDetectionTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/download/CDK32DownloadRuntimeTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/download/DownloadContainerRuntimeDefaultSettingsTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/download/DownloadRuntimesWizardTest.java
- test-framework/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/core/enums/CDKVersion.java
> Adding missing CDK versions, minishift version, reducing all tests suite

- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/internal/cdk/server/ui/CDK32ServerWizardFragment.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/internal/cdk/server/ui/CDK3ServerWizardFragment.java
> Overriding validateHomeDirectory with boolean param - fixes JBIDE-26854

- plugins/org.jboss.tools.openshift.cdk.server/plugin.xml
- plugins/org.jboss.tools.openshift.cdk.server/resources/whitelistGenerator.sh
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/internal/cdk/server/core/adapter/VersionUtil.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/internal/cdk/server/core/detection/MinishiftDownloadRuntimesProvider.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/internal/cdk/server/core/detection/MinishiftVersionLoader.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/internal/cdk/server/core/detection/UnifiedMinishiftRuntimeDetector.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/internal/cdk/server/ui/view/CDKActionProvider.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/internal/crc/server/ui/CRC100ServerWizardFragment.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/internal/crc/server/ui/detection/MissingPullSecretResolutionProvider.java
> [JBIDE-26871] Crc dlrt

- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/internal/crc/server/ui/CRC100ServerWizardFragment.java
> [JBIDE-26873] CRC wiz: correct vert align of "CRC Pull Secret File"

- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/internal/cdk/server/core/adapter/AbstractCDKPoller.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/internal/cdk/server/core/adapter/CDK32Poller.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/internal/cdk/server/core/adapter/CDK32Server.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/internal/cdk/server/core/adapter/CDK3Server.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/internal/cdk/server/core/adapter/controllers/AbstractCDKLaunchController.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/internal/cdk/server/core/adapter/controllers/AbstractCDKShutdownController.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/internal/cdk/server/core/adapter/controllers/CDK3LaunchController.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/internal/cdk/server/core/adapter/controllers/CDKLaunchController.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/internal/cdk/server/core/adapter/controllers/CDKLaunchUtility.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/internal/cdk/server/core/listeners/CDKLaunchEnvironmentUtil.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/internal/cdk/server/ui/AbstractLocationSection.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/internal/cdk/server/ui/CDK32CredentialSection.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/internal/cdk/server/ui/CDKCredentialSection.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/internal/cdk/server/ui/view/CDKActionProvider.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/internal/crc/server/core/adapter/controllers/CRC100LaunchController.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/internal/crc/server/core/adapter/controllers/CRC100ShutdownController.java
> corrected code according to sonar complaints

- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/internal/cdk/server/core/detection/MinishiftVersionLoader.java
> JBIDE-26907 - crc version string has changed

- plugins/org.jboss.tools.openshift.cdk.server/plugin.properties
> [JBIDE-26905] removed (Tech Preview) from CRC server adapter type

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/WatchManager.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/internal/test/ui/models/ConnectionWrapperTest.java
> [JBIDE-26697] dont watch unnecessary events for Event, PVC and Template

- plugins/org.jboss.tools.openshift.cdk.server/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/internal/crc/server/ui/CRC100ServerWizardFragment.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/internal/crc/server/ui/CRCLocationSection.java
> JBIDE-26878 - improve validation of pullsecret file

- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/internal/cdk/server/core/listeners/CDKOpenshiftUtility.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/internal/cdk/server/core/registry/CDKRegistryProvider.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/internal/crc/server/core/listeners/ConfigureCRCFrameworksListener.java
- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/common/ui/connection/CredentialsPrompter.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/connection/Connection.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/models/ConnectionWrapper.java
This fixes 
* https://issues.jboss.org/browse/JBIDE-26869 
* and https://issues.jboss.org/browse/JBIDE-26848
> [JBIDE-26869,JBIDE-26848] authorize & prompt when refreshing explorer conn

- itests/org.jboss.tools.openshift.ui.bot.test/pom.xml
- itests/org.jboss.tools.openshift.ui.bot.test/resources/os4templates/nodejs.json
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/OpenShift4StableBotTests.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/adapter/PublishChangesOS4Test.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/adapter/ServerAdapterFromResourceOS4Test.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/advanced/CreateResourcesOS4Test.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/advanced/DeleteResourceOS4Test.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/advanced/EditResourceLimitsOS4Test.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/advanced/ImportApplicationOS4Test.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/advanced/InteligentDeleteResourceOS4Test.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/advanced/ScalingOS4Test.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/advanced/TriggerBuildOS4Test.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/requirement/OpenShiftResources.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/utils/TestUtils.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/wizard/v3/OpenShift3ConnectionWizard.java
> OpenShift4 Integration tests fixes

- itests/org.jboss.tools.cdk.ui.bot.test/META-INF/MANIFEST.MF
- itests/org.jboss.tools.cdk.ui.bot.test/pom.xml
- jacoco-report/pom.xml
- plugins/pom.xml
- pom.xml
- tests/org.jboss.tools.openshift.cdk.server.test/META-INF/MANIFEST.MF
- tests/org.jboss.tools.openshift.cdk.server.test/pom.xml
- tests/pom.xml
> JBIDE-26653 Sonar settings update

- tests/org.jboss.tools.openshift.egit.test/src/org/jboss/tools/openshift/egit/internal/test/EGitUtilsTest.java
- tests/org.jboss.tools.openshift.egit.test/src/org/jboss/tools/openshift/egit/internal/test/util/TestRepository.java
> [JBIDE-26999] disabled commit signing in TestRepository

- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/internal/crc/server/core/listeners/ConfigureCRCFrameworksListener.java
- plugins/org.jboss.tools.openshift.client/.classpath
- plugins/org.jboss.tools.openshift.client/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.client/pom.xml
- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/utils/OpenShiftUIUtils.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/explorer/OpenShiftExplorerContentProvider.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/property/ConnectionProperties.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/property/ConnectionPropertySource.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/property/OpenShiftPropertySourceAdapterFactory.java
> [JBIDE-26869,JBIDE-26915] try reconnecting to crc & use latest client 8.1.1-SNAPSHOT

- tests/org.jboss.tools.openshift.test/META-INF/MANIFEST.MF
- tests/org.jboss.tools.openshift.test/resources/test-tools.json
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/common/ui/utils/OdoDownloadHelperTest.java
> JBIDE-26993: Provide download infrastructure for cli

- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/CDKAbstractTest.java
- plugins/org.jboss.tools.openshift.cdk.server/plugin.properties
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/internal/crc/server/core/adapter/CRC100Server.java
- test-framework/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/core/label/CDKLabel.java
> [JBIDE-26971] renamed CodeReady Containers 1.0 to 1.0+

- itests/org.jboss.tools.openshift.ui.bot.test/pom.xml
> JBIDE-27020 Update URL to m2e code quality plugins for ITests

- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/internal/cdk/server/core/detection/UnifiedMinishiftRuntimeDetector.java
> fixed minishift binary detection

- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/internal/crc/server/ui/CRC100ServerWizardFragment.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/internal/crc/server/ui/CRCLocationSection.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/internal/crc/server/ui/PullSecretValidation.java
> [JBIDE-27047] Read <20k of pull secret, validate in background

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/preferences/IOpenShiftCoreConstants.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/handler/AbstractOpenShiftCliHandler.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/preferences/OpenShiftPreferencePage.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/ServerSettingsWizardPage.java
> [JBIDE-27042] corrected link to download page for  oc binary

- plugins/org.jboss.tools.openshift.client/.classpath
- plugins/org.jboss.tools.openshift.client/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.client/build.properties
- plugins/org.jboss.tools.openshift.client/pom.xml
> [JBIDE-27017] bump openshift-restclient-java to 8.1.1.Final

- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/CDK32IntegrationTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/CDK32ServerAdapterProfilesTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/CDKServerAdapterAbstractTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/CDKServerAdapterSetupCDKTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/MinishiftServerAdapterProfilesTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/MinishiftServerAdapterTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/openshift/CDKImageRegistryUrlDiscoveryFailureTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/openshift/CDKImageRegistryUrlDiscoveryTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/openshift/CDKImageRegistryUrlValidatorTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/editor/CDK32ServerEditorTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/editor/MinishiftServerEditorTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/editor/launch/CDKLaunchConfigurationTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/runtime/CDK32RuntimeDetectionTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/runtime/CRCRuntimeDetectionTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/CRCServerWizardTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/download/CRCDownloadRuntimeTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/download/DownloadContainerRuntimeDefaultSettingsTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/download/DownloadRuntimesWizardTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/download/MinishiftDownloadRuntimeTest.java
- test-framework/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/core/enums/CDKVersion.java
- test-framework/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/core/label/CDKLabel.java
> Update cdk, crc, minishift

- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/internal/crc/server/ui/CRC100ServerWizardFragment.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/internal/crc/server/ui/PullSecretValidation.java
> JBIDE-27064: Pull secret validation did not enable Finish button

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/odo/OdoConsole.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/common/core/connection/HumanReadableX509CertificateTest.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/util/SSLCertificateMocks.java
> [JBIDE-27140] fixed cert test by updating ssl certificate for www.redhat.com

- plugins/org.jboss.tools.openshift.client/.classpath
- plugins/org.jboss.tools.openshift.client/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.client/pom.xml
> use openshift-restclient-java 8.1.2.Final

- plugins/org.jboss.tools.openshift.client/.classpath
- plugins/org.jboss.tools.openshift.client/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.client/pom.xml
> use openshift-restclient-java 9.0.0.Final

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/applicationexplorer/CreateComponentWizardPage.java
> JBIDE-27284 Change labels in CreateComponentWizard

- itests/org.jboss.tools.cdk.ui.bot.test/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.common.core/src/org/jboss/tools/openshift/internal/common/core/UsageStats.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/odo/OdoCli.java
- test-framework/org.jboss.tools.cdk.reddeer/META-INF/MANIFEST.MF
> JBIDE-27287: Add reporting to odo experience

- plugins/org.jboss.tools.openshift.client/META-INF/MANIFEST.MF
> JBIDE-27361: fix NoClassDefFoundError by adding missing dependencies back to classpath.

- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/CDK32IntegrationTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/CDK32ServerAdapterProfilesTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/CDKServerAdapterSetupCDKTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/CDKWrongCredentialsTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/openshift/CDKImageRegistryUrlDiscoveryFailureTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/openshift/CDKImageRegistryUrlDiscoveryTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/openshift/CDKImageRegistryUrlValidatorTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/editor/CDK32ServerEditorTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/editor/launch/CDKLaunchConfigurationTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/runtime/CDK32RuntimeDetectionTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/runtime/CRCRuntimeDetectionTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/download/CDK32DownloadRuntimeTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/download/CRCDownloadRuntimeTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/download/DownloadContainerRuntimeDefaultSettingsTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/download/DownloadLatestContainerRuntimeTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/download/DownloadRuntimesWizardTest.java
- test-framework/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/core/enums/CDKVersion.java
> Adding missing CRC and CDK versions

- itests/org.jboss.tools.openshift.ui.bot.test/META-INF/MANIFEST.MF
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/AbstractODOTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/OpenShiftODOTests.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/odo/ConnectionODOCommandsTests.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/odo/CreateComponentODOTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/odo/CreateServiceODOTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/odo/LoginODOTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/odo/ProjectManagementODOTest.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/dialogs/InputDialog.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/requirement/CleanOpenShiftODOConnectionRequirement.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/requirement/OpenShiftODOConnectionRequirement.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/requirement/OpenShiftODOProjectRequirement.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/utils/OpenShiftLabel.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/view/OpenShiftApplicationExplorerView.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/view/resources/AbstractOpenShiftApplicationConnection.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/view/resources/AbstractOpenShiftApplicationExplorerItem.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/view/resources/OpenShiftODOConnection.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/view/resources/OpenShiftODOProject.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/wizard/AbstractOpenShiftApplicationWizard.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/wizard/CreateComponentWizard.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/wizard/CreateServiceWizard.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/wizard/page/CreateComponentWizadPage.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/wizard/page/CreateServiceWizadPage.java
> JBIDE-27060 ODO OpenShift ITests

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/odo/ServiceTemplate.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/odo/ServiceTemplatesDeserializer.java
- plugins/org.jboss.tools.openshift.ui/resources/tools.json
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/applicationexplorer/CreateComponentWizardPage.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/applicationexplorer/CreateServiceWizardPage.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/applicationexplorer/ServiceTemplateColumLabelProvider.java
fix also service catalog listing
> JBIDE-27366: switch to odo 1.2.3

- itests/org.jboss.tools.openshift.ui.bot.test/pom.xml
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/OpenShiftInteropTests.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/odo/LoginODOTest.java
> JBIDE-27441 OpenShift Interop Tests suite

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/odo/ComponentTypesDeserializer.java
- plugins/org.jboss.tools.openshift.ui/resources/tools.json
> JBIDE-27454: switch to odo 1.2.6

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/odo/Odo.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/handler/applicationexplorer/CreateServiceHandler.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/models/applicationexplorer/OdoProjectDecorator.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/odo/OdoCli.java
> JBIDE-27457: Create service silent if no catalog installed

- itests/org.jboss.tools.openshift.ui.bot.test/resources/os4templates/nodejs.json
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/adapter/ServerAdapterFromResourceTest.java
> JBIDE-26792 Fix ServerAdapterFromResourceTest

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/ocbinary/OCBinaryValidator.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/internal/test/core/preferences/OCBinaryValidatorTest.java
> [JBIDE-27068] recognize okd 4 client binaries

- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/explorer/BaseExplorerLabelProvider.java
> JBIDE-27486 Increase label limit in BaseExplorer

- plugins/org.jboss.tools.openshift.client/.classpath
- plugins/org.jboss.tools.openshift.client/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.client/pom.xml
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/core/connection/ConnectionTestUtils.java
> [JBIDE-27487] use latest openshift-restclient-java 9.0.1.Final

- itests/org.jboss.tools.openshift.ui.bot.test/META-INF/MANIFEST.MF
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/AbstractODOTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/OpenShiftInteropTests.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/connection/v3/CreateNewConnectionTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/odo/LoginODOTest.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/condition/ODOConnectionExists.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/condition/ODOIsDownloaded.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/condition/ODOProjectIsDeleted.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/requirement/CleanOpenShiftODOConnectionRequirement.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/requirement/OpenShiftODOProjectRequirement.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/view/OpenShiftApplicationExplorerView.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/view/resources/OpenShiftODOConnection.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/view/resources/OpenShiftODOProject.java
> JBIDE-27364 OpenShift ODO ITests improvements

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/handler/applicationexplorer/CreateServiceHandler.java
> JBIDE-27485: no UI/dialog shown when there is no service in catalog

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/handler/applicationexplorer/LoginHandler.java
> JBIDE-27528 Refresh view after login to cluster

- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/basic/BuilderImageApplicationWizardHandlingTest.java
> JBIDE-26317 BuilderImageApplicationWizardHandlingTest ITest fix

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/odo/ComponentDescriptorsDeserializer.java
- plugins/org.jboss.tools.openshift.ui/resources/tools.json
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/odo/OdoCli.java
- tests/org.jboss.tools.openshift.test/resources/component-descriptor-test.json
> JBIDE-27530: switch to odo 2.0 and verify S2I

- plugins/org.jboss.tools.openshift.cdk.server/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/internal/crc/server/core/adapter/CRC100Poller.java
> Fix JBIDE-27499 - use json output format for crc status

- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/condition/ODOApplicationIsDeleted.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/condition/ODOComponentIsDeleted.java
> JBIDE-27555: openshift build is broken

- itests/org.jboss.tools.openshift.ui.bot.test/resources/devfiles/java-maven/devfile.yaml
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/AbstractODOTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/OpenShiftODOTests.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/odo/CreateVertxDevfileComponentWithLocalDevfileODOTest.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/odo/Odo.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/handler/applicationexplorer/CreateComponentHandler.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/models/applicationexplorer/OdoProjectDecorator.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/odo/OdoCli.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/applicationexplorer/CreateComponentModel.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/applicationexplorer/CreateComponentWizardPage.java
> JBIDE-27553: Add support for project devfile

- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/AbstractODOTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/odo/CreateDevfileComponentODOTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/odo/CreateS2IComponentODOTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/odo/CreateVertxDevfileComponentWithStarterODOTest.java
- plugins/org.jboss.tools.openshift.common.core/src/org/jboss/tools/openshift/common/core/utils/ProjectUtils.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/odo/ComponentTypeInfo.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/odo/JSonParser.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/odo/Odo.java
- plugins/org.jboss.tools.openshift.ui/resources/tools.json
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/handler/applicationexplorer/CreateComponentHandler.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/models/applicationexplorer/OdoProjectDecorator.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/odo/OdoCli.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/applicationexplorer/CreateComponentModel.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/applicationexplorer/CreateComponentWizardPage.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/utils/OpenShiftLabel.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/wizard/page/CreateComponentWizadPage.java
> JBIDE-27563: Add support for starters

- itests/org.jboss.tools.openshift.ui.bot.test/resources/os4templates/eap73-basic-s2i-helloworld.json
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/AbstractODOTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/advanced/InteligentDeleteResourceTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/advanced/TriggerBuildOS4Test.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/advanced/TriggerBuildTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/basic/LabelsTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/create/CreateApplicationFromTemplateOS4Test.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/create/CreateApplicationFromTemplateTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/connection/v3/ConnectionPropertiesTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/connection/v3/ConnectionWizardHandlingTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/connection/v3/CreateNewConnectionTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/odo/CreateServiceODOTest.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/view/resources/OpenShiftODOConnection.java
> OpenShift ITests updates

- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/internal/crc/server/core/adapter/CRC100Poller.java
> JBIDE-27589 Handling crc 1.17+ status reporting of non started machine

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/odo/OdoCli.java
> added UsageStats label for devfile or s2i components

- plugins/org.jboss.tools.openshift.ui/resources/tools.json
> Switch to odo 2.0.4

- itests/org.jboss.tools.openshift.ui.bot.test/pom.xml
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/OpenShiftInteropTests.java
> JBIDE-27576 Add ODO profile in ITests

- features/pom.xml
- plugins/org.jboss.tools.openshift.common.core/.classpath
- plugins/org.jboss.tools.openshift.ui/.classpath
> JBIDE-27614 : fix tycho 2.2 update issues

- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/OpenShiftODOTests.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/odo/ConnectionODOCommandsTests.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/odo/CreateServiceODOTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/odo/LoginODOTest.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/view/resources/AbstractOpenShiftApplicationExplorerItem.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/view/resources/OpenShiftODOApplication.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/view/resources/OpenShiftODOComponent.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/view/resources/OpenShiftODOConnection.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/view/resources/OpenShiftODOProject.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/widget/terminal/TerminalContainsText.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/widget/terminal/TerminalView.java
> JBIDE-27576 OpenShift ODO ITests updates

- plugins/org.jboss.tools.openshift.core/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.core/build.properties
- plugins/org.jboss.tools.openshift.core/plugin.xml
- plugins/org.jboss.tools.openshift.core/resources/devfile.json
- tests/org.jboss.tools.openshift.test/META-INF/MANIFEST.MF
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/internal/test/core/devfile/DevfileTest.java
> JBIDE-27611: Provides devfile code assist and validation

- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/AbstractODOTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/OpenShiftODOTests.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/odo/CreatePythonDevfileComponentWithStarterODOTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/odo/DebugPythonDevfileComponentODOTest.java
- plugins/org.jboss.tools.openshift.core/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.core/plugin.xml
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/OpenShiftCoreConstants.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/odo/DebugInfo.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/odo/JSonParser.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/odo/Odo.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/stack/PythonRemoteStackDebugger.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/handler/applicationexplorer/DebugHandler.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/models/applicationexplorer/OdoProjectDecorator.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/odo/OdoCli.java
**This requires a merged patch on the LSP4E side so latest snapshot is required.**
> JBIDE-27612: add support for Python

- plugins/org.jboss.tools.openshift.ui/resources/tools.json
> JBIDE-27719: Switch to odo 2.0.7

- .github/workflows/build_test.yml
- .github/workflows/publish_reports.yml
> Jbide 27705

- .github/workflows/publish_reports.yml
> Update publishing pattern

- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/internal/cdk/server/ui/view/SetupCDKJob.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/internal/crc/server/core/adapter/CRC100Server.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/internal/crc/server/core/adapter/controllers/CRC100LaunchController.java
- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/internal/crc/server/ui/view/SetupCRCJob.java
> JBIDE-27739 - prompt for telemetry permission during crc setup

- plugins/org.jboss.tools.openshift.client/.classpath
- plugins/org.jboss.tools.openshift.client/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.client/pom.xml
- plugins/org.jboss.tools.openshift.common.core/src/org/jboss/tools/openshift/internal/common/core/UsageStats.java
- plugins/org.jboss.tools.openshift.ui/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/validator/CountryCodeValidator.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/validator/PhoneNumberValidator.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/applicationexplorer/LoginWizardPage.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/applicationexplorer/sandbox/SandboxAPI.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/applicationexplorer/sandbox/SandboxLoginPage.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/applicationexplorer/sandbox/SandboxModel.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/applicationexplorer/sandbox/SandboxProcessor.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/applicationexplorer/sandbox/SandboxWizard.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/applicationexplorer/sandbox/SandboxWorkflowPage.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/connection/OAuthBrowser.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/connection/OAuthDialog.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/internal/ui/wizard/applicationexplorer/sandbox/CountryCodeValidatorTest.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/internal/ui/wizard/applicationexplorer/sandbox/PhoneNumberValidatorTest.java
> JBIDE-27680: Login/bootstrap Developer Sandbox

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/applicationexplorer/sandbox/SandboxLoginPage.java
> JBIDE-27788 : fix wizard NPE when SSO fails.

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/odo/JSonParser.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/odo/Odo.java
- plugins/org.jboss.tools.openshift.ui/resources/tools.json
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/applicationexplorer/OpenShiftApplicationExplorerContentProvider.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/handler/applicationexplorer/CreateComponentHandler.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/models/applicationexplorer/OdoProjectDecorator.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/odo/ExecHelper.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/odo/OdoCli.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/applicationexplorer/CreateComponentModel.java
> JBIDE-27837: Migrate to odo v2.2.0

- plugins/org.jboss.tools.openshift.ui/.classpath
- plugins/org.jboss.tools.openshift.ui/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.ui/pom.xml
> fix CVE-2019-10086 from snyk analysis

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/applicationexplorer/CreateComponentWizardPage.java
> JBIDE-27846: Push checkbox not visible in create component wizard

- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/connection/v3/CreateNewConnectionTest.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/requirement/CleanOpenShiftODOConnectionRequirement.java
> JBIDE-27843 OpenShift Interop test fixes

- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/AbstractODOTest.java
- itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/odo/CreateDevfileComponentFromRegistryODOTest.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/odo/DevfileComponentType.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/odo/Odo.java
- plugins/org.jboss.tools.openshift.ui/plugin.xml
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/handler/applicationexplorer/CreateComponentHandler.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/condition/ODORegistryIsDeleted.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/utils/OpenShiftLabel.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/view/OpenShiftApplicationExplorerView.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/view/resources/OpenShiftODOConnection.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/view/resources/OpenShiftODODevfile.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/view/resources/OpenShiftODORegistries.java
- test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/view/resources/OpenShiftODORegistry.java
> JBIDE-27676: Create component from component types and starters

- plugins/org.jboss.tools.openshift.ui/icons/readme.txt
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/OpenShiftImages.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/applicationexplorer/OpenShiftApplicationExplorerLabelProvider.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/applicationexplorer/ComponentTypeColumLabelProvider.java
> JBIDE-27870: Add icons to registries

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/applicationexplorer/LoginWizardPage.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/applicationexplorer/sandbox/SandboxWorkflowPage.java
> JBIDE-27788: dont launch job in paint listener

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/applicationexplorer/LoginWizardPage.java
> LoginWizard: show required info not error when all fields are empty

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/applicationexplorer/sandbox/SandboxLoginPage.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/applicationexplorer/sandbox/SandboxWorkflowPage.java
depends on #2008 which has to be merged first
> JBIDE-27896: disable next/finish as long as sandbox not ok

- plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/explorer/BaseOpenShiftExplorerView.java
> JBIDE-27905: only trigger link for left mouse button

- plugins/org.jboss.tools.openshift.ui/resources/tools.json
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/odo/ExecHelper.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/odo/OdoCli.java
> JBIDE-27859: update to odo 2.2.2

- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/internal/cdk/server/core/detection/AbstractCDKRuntimeDetector.java
> Partially provides a fix for JBIDE-27871

- plugins/org.jboss.tools.openshift.common.core/src/org/jboss/tools/openshift/internal/common/core/UsageStats.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/handler/applicationexplorer/LoginHandler.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/models/applicationexplorer/ApplicationExplorerUIModel.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/odo/ClusterHelper.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/odo/ClusterInfo.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/applicationexplorer/OpenShiftApplicationExplorerContentProviderTest.java
> JBIDE-27916: added openshift and kubernetes version in telemetry 

- plugins/org.jboss.tools.openshift.common.core/src/org/jboss/tools/openshift/internal/common/core/UsageStats.java
- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/odo/ClusterHelper.java
> JBIDE-27919: Fix NPE in telemetry

- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/CDK32IntegrationTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/CDK32ServerAdapterProfilesTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/CDKServerAdapterSetupCDKTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/openshift/CDKImageRegistryUrlDiscoveryFailureTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/openshift/CDKImageRegistryUrlDiscoveryTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/openshift/CDKImageRegistryUrlValidatorTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/editor/CDK32ServerEditorTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/editor/launch/CDKLaunchConfigurationTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/runtime/CDK32RuntimeDetectionTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/runtime/CRCRuntimeDetectionTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/download/CRCDownloadRuntimeTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/download/DownloadContainerRuntimeDefaultSettingsTest.java
- itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/download/DownloadRuntimesWizardTest.java
- test-framework/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/core/enums/CDKVersion.java
- test-framework/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/server/ui/wizard/CredentialsWizardPage.java
- test-framework/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/server/ui/wizard/NewServerContainerWizardPage.java
> Update CRC, CDK and minishift tests + some fixes

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/models/applicationexplorer/ApplicationExplorerUIModel.java
> JBIDE-27980: OpenShift Application Explorer is not correctly refreshed

- pom.xml
> Fix enforceer rule check for excluding alizer until release version is done.

- plugins/org.jboss.tools.openshift.client/.classpath
- plugins/org.jboss.tools.openshift.client/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.client/pom.xml
> JBIDE-28005: use openshift-restclient-java-9.0.2.Final

- plugins/org.jboss.tools.openshift.core/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/stack/JavaRemoteStackDebugger.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/stack/NodeRemoteStackDebugger.java
- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/stack/PythonRemoteStackDebugger.java
> JBIDE-28252: Cannot debug in OpenShift Application Explorer

- plugins/org.jboss.tools.openshift.ui/.classpath
- plugins/org.jboss.tools.openshift.ui/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.openshift.ui/pom.xml
> Fix alizer 0.1.0 jar qualifier

- plugins/org.jboss.tools.openshift.ui/resources/tools.json
> JBIDE-28300: update to odo 2.5.0

- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/internal/cdk/server/core/detection/UnifiedMinishiftRuntimeDetector.java
> Fixes JBIDE-27728 - add an exists check for folder

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/odo/ServiceTemplatesDeserializer.java
- tests/org.jboss.tools.openshift.test/resources/service-template-required-test.json
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/internal/test/core/odo/ServiceTemplateRequiredTest.java
> JBIDE-28314: Can't create service on Red Hat Developer Sandbox

- plugins/org.jboss.tools.openshift.ui/resources/tools.json
> JBIDE-28461: update to odo 2.5.1

- tests/org.jboss.tools.openshift.egit.test/src/org/jboss/tools/openshift/egit/internal/test/EGitUtilsTest.java
- tests/org.jboss.tools.openshift.egit.test/src/org/jboss/tools/openshift/egit/internal/test/util/TestProject.java
- tests/org.jboss.tools.openshift.egit.test/src/org/jboss/tools/openshift/egit/internal/test/util/TestRepository.java
- tests/org.jboss.tools.openshift.egit.test/src/org/jboss/tools/openshift/egit/internal/test/util/TestUtils.java
> JBIDE-27197: fix random egit test failures

- plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/internal/cdk/server/core/detection/MinishiftVersionLoader.java
> JBIDE-28509: NPE during starting CRC 2.3.0

- itests/org.jboss.tools.openshift.ui.bot.test/pom.xml
> Update itests surefire.timeout

- plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/util/MavenProfile.java
> JBIDE-28642: fix unit tests

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/connection/OAuthBrowser.java
> DevSandBox login is broken on windows, fixes JBIDE-28548

- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/core/server/debug/OpenShiftDebugModeTest.java
- tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/wizard/newapp/NewApplicationWizardModelTest.java
> JBIDE-28845: fix hamcrest resolution errors

- plugins/org.jboss.tools.openshift.ui/resources/tools.json
> JBIDE-28856: update to odo 3.6.0

- plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/odo/OdoCli.java
> JBIDE-28822: Deleting a component throws an error in Error Log View

- jacoco-report/pom.xml
> JBIDE-29058: fix build after TP update
