site/category.xml
PR #536 did not add features to `category.xml` thus nothing in the actual generated site.
Note: this does not make it available in main jboss tools updatesite yet so that step is still needed.
=> JBIDE-19162 add openshift v3 feature + test feature to category.xml

plugins/org.jboss.tools.openshift.common.core/src/org/jboss/tools/openshift/internal/common/core/UsageStats.java
Replaced countEvent() by trackEvent(). So we will send all events right away instead of counting them for 24 hours.
=> JBIDE-20167 Openshift Tooling Usage Tracking.

plugins/org.jboss.tools.openshift.common.ui/plugin.xml, plugins/org.jboss.tools.openshift.ui/plugin.xml, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/handler/RefreshResourceHandler.java
I don't know how we can get the parent Connection node from the error node, from the ISelection, 
so I didn't add the Refresh menu
At least hiding the new Connection menu from error nodes should be enough for now
=> [JBIDE-19584] Hide 'New Connection' menu from OpenShiftException nodes in OS Explorer

plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/job/CreateApplicationFromTemplateJob.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/newapp/NewApplicationWizard.java, tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/job/CreateApplicationFromTemplateJobTest.java
=> [JBIDE-20407] Validate resource names before app creation

plugins/org.jboss.tools.openshift.express.core/src/org/jboss/tools/openshift/express/internal/core/server/OpenShiftServerExtendedProperties.java
JBIDE-21116 - openshift server adapter doesn't need or benefit from xml / fileset enhancements
=> JBIDE-21116 - openshift server adapter doesn't need or benefit from 

plugins/org.jboss.tools.openshift.common.core/src/org/jboss/tools/openshift/common/core/server/ServerUtils.java, plugins/org.jboss.tools.openshift.express.core/src/org/jboss/tools/openshift/express/internal/core/server/ExpressServer.java, plugins/org.jboss.tools.openshift.express.core/src/org/jboss/tools/openshift/express/internal/core/server/ExpressServerUtils.java
=> [JBIDE-21318] use proper OpenShift version in server labels

plugins/org.jboss.tools.openshift.core/META-INF/MANIFEST.MF, plugins/org.jboss.tools.openshift.core/plugin.xml, plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/preferences/OCBinaryName.java, plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/preferences/OpenShiftCorePreferenceInitializer.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/handler/AbstractOpenShiftCliHandler.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/preferences/OpenShiftPreferencePage.java
OpenShiftCorePreferenceInitializer is implemented. It sets the default preference value at the first access to the preference, which can be either at preference page or any other code that needs it.
Definition of OCBinaryName is moved as is from OpenShiftPreferencePage into OpenShiftCorePreferenceInitializer. It remains visible from OpenShiftPreferencePage.
=> JBIDE-21301 Preferences: path to OC binary is not shown on OpenShift 3 page if binary is on $PATH

plugins/org.jboss.tools.openshift.common.core/src/org/jboss/tools/openshift/common/core/connection/ConnectionsRegistry.java
Work with listeners should be synchronized, iteration at firing should be done on copy.
The number one candidate to modify listeners during firing is BaseExplorerContentProvider.inputChanged().
=> JBIDE-21414 Application wizard: ConcurrentModificationException when creating a new appliaction

plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/importapp/ImportApplicationWizardModel.java, tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/application/ImportApplicationWizardModelTest.java
I could not come up with a reasonable regex to solve the problem.
Actually, a piece of intricate regex looks like so much of compiled byte code put into the source.
I suggest good old String.endsWith and String.lastIndexOf for extracting project name of uri.
Tests should take care of project name being not null with good uri.
=> JBIDE-21443 NullPointerException when trying to import a BuildConfig as a new application from OpenShift 3

plugins/org.jboss.tools.openshift.common.core/src/org/jboss/tools/openshift/common/core/utils/StringUtils.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/explorer/OpenShiftExplorerLabelProvider.java, tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/common/core/util/StringUtilsTest.java, tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/explorer/OpenShiftExplorerLabelProviderTest.java
Length of label text returned by OpenShiftExplorerLabelProvider is limited.
This provider is used not only in explorer but in many viewers in wizards.
It is not user friendly to display the entire value if its length is unreasonably large.
In this solution, ellipses are applied if length exceeds 120 symbols.
=> JBIDE-21069 Application wizard: long project display names mess up project selection

plugins/org.jboss.tools.openshift.client/.project, plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/connection/Connection.java, plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/connection/IOpenShiftConnection.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/explorer/OpenShiftExplorerContentProvider.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/models/DeploymentResourceMapper.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/models/IProjectAdapter.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/models/IProjectCache.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/models/IResourceCache.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/models/ObservableResourceCache.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/models/OpenShiftProjectCache.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/models/OpenShiftProjectUIModel.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/ServerSettingsViewModel.java, tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/AllTestsSuite.java, tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/models/OpenShiftProjectCacheTest.java
cc @fbricon @mlabuda @adietish
=> [JBIDE-21590] Add project cache to handle connection refresh issues

plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/OpenShiftServerBehaviour.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/DeployImageWizardModel.java, tests/org.jboss.tools.openshift.test/META-INF/MANIFEST.MF, tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/models/DeployImageWizardModelTest.java
=> [JBIDE-21698] fix image name parsing

plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/DeployImagePage.java
Rendering connection label:
- in wizards - ConnectionColumLabelProvider,
- in explorer - OpenShiftExplorerLabelProvider.
=> JBIDE-21734 Deploying of a docker image from docker explorer has ambiguous connection

tests/org.jboss.tools.openshift.test/META-INF/MANIFEST.MF
replaced import-packages directive with additional entries in the required-bundles
=> JBIDE-21808 - outdated "import package" declaration in "org.jboss.tools.openshift.test"

plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/DeployImagePage.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/DeployImageWizardModel.java
Ignoring dnagling and intermediate images in the content assist proposals.
Using Lambda Expression instead of old for-loop based.
=> JBIDE-21802 - Content assist for image names in "Deploy Docker Image" wizard

plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/validator/ServiceNameValidator.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/DeployImagePage.java, tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/validator/AbstractValidatorTest.java, tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/validator/LabelValueValidatorTest.java, tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/validator/ProjectNameValidatorTest.java, tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/validator/ServiceNameValidatorTest.java
This PR
* Renames deployimagename validator to servicenamevalidator
* Adds validation tests
* Fixes name validation when model#setName is called by model#setImage
=> [JBIDE-21846] fix deploy image name validator when set by setting the  image

plugins/org.jboss.tools.openshift.core/META-INF/MANIFEST.MF, plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/portforwarding/PortForwardingUtils.java, plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/portforwarding/package-info.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/portforwading/PortForwardingWizardModel.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/portforwading/PortForwardingWizardPage.java, tests/org.jboss.tools.openshift.test/META-INF/MANIFEST.MF, tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/internal/core/portforwarding/PortForwardingUtilsTest.java, tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/internal/core/portforwarding/package-info.java
Refactored the PortForwardingWizardModel to move all the port-forwarding
core functionnalities in a new PortforwardingUtils class
in plugins/org.jboss.tools.openshift.core.
Refactored the PortForwardingWizardPage to use local variables instead
of fields for the widgets.
=> JBIDE-21701 - Enable port forwarding on a given pod and a given debug port

plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/RSync.java
Using the new method in IServerConsoleWriter to avoid activating the console
when new content is written. The console is only opened when it is created,
ie, at the first 'rsync' operation.
=> JBIDE-21949 - Allow user to turn on/off showing console when output changes

plugins/org.jboss.tools.openshift.core/META-INF/MANIFEST.MF, plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/OpenShiftServerUtils.java, plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/behavior/OpenShiftLaunchController.java, plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/models/PortSpecAdapter.java, plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/server/debug/DebuggingContext.java, plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/server/debug/DeploymentConfigListenerJob.java, plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/server/debug/IDebugListener.java, plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/server/debug/OpenShiftDebugUtils.java, plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/util/ResourceUtils.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/DeployImageWizardModel.java, tests/org.jboss.tools.openshift.test/META-INF/MANIFEST.MF, tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/core/server/OpenShiftDebugUtilsTest.java, tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/models/DeployImageWizardModelTest.java, tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/wizard/deployimage/PortSpecAdapterTest.java
=> [JBIDE-21625] Enable debug mode for OpenShift 3 server adapter

plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/RSync.java, plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/behavior/OpenShiftLaunchController.java, plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/portforwarding/PortForwardingUtils.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/job/PodLogsJob.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/portforwading/PortForwardingWizardModel.java, tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/internal/core/portforwarding/PortForwardingUtilsTest.java
Using the OpenShiftBinaryOptions to pass some options to the 'oc'
command that will be run by the client, to make sure that the '.git'
folder is still excluded during rsync and that the server certificates
are not verified during the TLS connection setup.
=> JBIDE-21999 - Error during rsync

plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/behavior/OpenShiftPublishController.java
=> JBIDE-21981 - fix error during rsync

tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/core/connection/ConnectionsChange.java, tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/explorer/OpenShiftExplorerContentProviderTest.java
* the test class ConnectionsChange releases a lock before it is updating its internal values (that the testing code then asserts).
* an [erroneous usage of mockito|https://groups.google.com/forum/?fromgroups#!topic/mockito/9WUvkhZUy90]. To simulate returned values for partial mocks one should use
doReturn(...).when(spy).method()
(and not when(...).thenReturn())
=> [JBIDE-22240] fixed testing code to fix build

plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/utils/TableViewerBuilder.java, plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/wizard/KeyValueWizardPage.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/common/EnvironmentVariablePage.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/common/EnvironmentVariablesPageModel.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/common/IEnvironmentVariablesPageModel.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/DeployImageWizardModel.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/DeploymentConfigPage.java
1. Button 'Reset All' is added.
2. Added env var is selected. Edited/reset env var keeps selection.
3. For user to see which env vars he added, and which values he edited, background of cells with added/edited values is set to a light grey color.
4. Implementing (2) allowed to enable buttons 'Reset' and 'Reset All' only when there is something they can change.
5. When 'Edit Environment Variable' is opened with uneditable Name field, value field is initially focused and value selected.
=> JBIDE-22263 Deploy Docker Wizard: Reset button on Deployment Configuration wizard page in Deploy Image could reset ALL env. vars

plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/validator/ResourceNameValidator.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/common/ResourceNameControl.java
Validating widget is restored. It is necessery to decorate widget with required/error marks.
=> JBIDE-21394 Deploy docker: "Resource Name" should not error (but "*" required) if empty

plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/property/tabbed/OpenShiftResourcePropertySection.java
The same approach that fixed column width at resizing (see JBIDE-21529) works for vertical layout. At least, on Ubuntu.
=> JBIDE-22306 Properties view freaks out on resize

plugins/org.jboss.tools.openshift.client/.classpath, plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/ICommonAttributes.java, plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/ImageStreamTagMetaData.java, plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/util/OpenShiftProjectUtils.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/job/CreateApplicationFromImageJob.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/job/DeployImageJob.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/DeployImageWizard.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/DeployImageWizardModel.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/IDeployImageParameters.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/newapp/ApplicationSourceTreeItems.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/newapp/fromimage/ApplicationSourceFromImageModel.java, tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/job/CreateApplicationFromImageJobTest.java, tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/job/DeployImageJobTest.java
cc @fbricon @adietish 
fixes how the imagestream is created and the container image for the deploymentconfig so that it is functionally similiar to 'oc new-app'
=> [JBIDE-22177] Fix imagestream creating when deploy image from docker

plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/newapp/ApplicationSourceListPage.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/newapp/TabFolderTraverseListener.java, tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/wizard/newapp/TabFolderTraverseListenerTest.java
1. Children widgets of tab items are included into the list
of controls traversed by tab key.
2. List is navigated with arrows while filter remains focused.
=> JBIDE-22316 Filter template + arrow down should focus on template list and navigate through templates

plugins/org.jboss.tools.openshift.common.core/src/org/jboss/tools/openshift/internal/common/core/job/AbstractDelegatingMonitorJob.java, plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/OpenShiftCommonUIActivator.java, plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/utils/OpenShiftUIUtils.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/DeployImageWizard.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/newapp/NewApplicationWizard.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/resource/NewResourceWizard.java, tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/common/ui/OpenShiftCommonUIActivatorTest.java, tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/util/UITestUtils.java
OpenShift Explorer is shown when creating the OpenShift Connection from the CDK server adapter or the regular New OpenShift Application wizard.
http://screencast.com/t/j6EWxqS2adP
=> [JBIDE-22278] Show OpenShift Explorer when a new Connection is created

plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/OpenShiftServerEditorSection.java
This is a fix in openshift. Separate PR will fix class DisableAllWidgetsJob in base.
=> JBIDE-22379 Server editor: closing it before the widgets are enabled ends up in "widget disposed" error

plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/connection/Connection.java
A fix to Connection.isConnected(), so that it would not call connect if
the connection is not authorizaed.
The other condition, that connect should be called only if srategy
instance is set, was already working.
=> JBIDE-22426

plugins/org.jboss.tools.openshift.cdk.server/about.properties
This is just a small addition to a previous commit on this topic
=> JBIDE-22120 Fix cdk plugin blurb string - should not say vagrant

plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/validator/ProjectDisplayNameValidator.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/project/NewProjectWizardPage.java, tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/validator/ProjectDisplayNameValidatorTest.java
The limit is, actually, set in swt Text and it is [platform dependent](http://help.eclipse.org/luna/topic/org.eclipse.platform.doc.isv/reference/api/org/eclipse/swt/widgets/Text.html#LIMIT). In my Fedora 23 
```
public int getTextLimit () {
checkWidget ();
if ((style & SWT.MULTI) != 0) return LIMIT;
int limit = OS.gtk_entry_get_max_length (handle);
return limit == 0 ? 0xFFFF : untranslateOffset (limit);
}
```
always returns 0xFFFF which is exactly 65536. So couldn't test it in a usual way, but just setting the limit lower for testing purposes.
However, i added ValidationStatus.error when input is bigger so that this check works in another OSs.
=> [JBIDE 21068] Set maximum length for display name for project wizard

tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/wizard/deployimage/search/DockerHubRegistryTest.java
Disabling the failing test until upstream is fixed.
=> JBIDE-22510 - Unable to display tags for jboss/wildfly Docker image

plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/job/DeployImageJob.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/DeployImageWizard.java, tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/job/DeployImageJobTest.java
cc @fbricon 
This skips resource creation if its determined to be an update of deploying an image.  I have not yet tested the create from app builder scenario that relies upon this, but its a first pass.  I suppose you are going to want some unit tests too...:)
=> [JBIDE-22515] Don't create resources when its an image update

plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/validator/URLValidator.java, tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/validator/URLValidatorTest.java
=> [JBIDE-22596] disable domain validation to cope with *.cdk urls

plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/newapp/fromtemplate/ApplicationSourceFromTemplateModel.java
The firing of parameters list change was happening before the default values were stored in the model. Fixed.
=> JBIDE-22545 Application Wizard: Default values in template parameters table are in italics

plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/wizard/KeyValueWizardPage.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/handler/ManageEnvironmentVariablesHandler.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/common/EnvironmentVariablePage.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/common/EnvironmentVariablesPageModel.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/common/IEnvironmentVariablesPageModel.java, tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/wizard/deployimage/DeployImageWizardModelTest.java
Any environment var can be deleted or renamed. The result of rename is shown as the sum of the deleted original var and added new var. A deleted original var is shown in the table in italic with text decoration '[deleted]'. User can restore it in one of the following ways: 1) select and push Restore, 2) select and push Edit, set value and finish, 3) Push Add, enter the same key (it is not prohibited since the var is marked deleted) and finish, 4) Rename another var to its name.
All these operations are consistent and show user which original vars are deleted/modified and which new are added.
The option to delete/rename original vars is implemented only for 'Manage Environment Variables' wizard. Other wizards are not affected.
=> JBIDE-22473 Environment Var Wizard: Cannot remove env vars

plugins/org.jboss.tools.openshift.common.core/src/org/jboss/tools/openshift/common/core/connection/IConnection.java, plugins/org.jboss.tools.openshift.common.core/src/org/jboss/tools/openshift/common/core/connection/NewConnectionMarker.java, plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/connection/ConnectionWizardPageModel.java, plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/utils/OpenShiftUIUtils.java, plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/utils/UIUtils.java, plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/connection/Connection.java, plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/connection/ConnectionsRegistryUtil.java, plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/util/ResourceUtils.java, plugins/org.jboss.tools.openshift.express.core/src/org/jboss/tools/openshift/express/internal/core/connection/ExpressConnection.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/comparators/ProjectViewerComparator.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/handler/DeployImageHandler.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/common/AbstractProjectPage.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/common/IProjectAware.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/connection/ConnectionEditor.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/connection/OAuthDetailView.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/DeployImagePage.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/DeployImageWizard.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/DeployImageWizardModel.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/IDeployImagePageModel.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/newapp/NewApplicationWizardModel.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/resource/NewResourceWizardModel.java, tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/common/ui/utils/ConnectionWizardPageModelTest.java, tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/core/connection/ConnectionFake.java, tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/core/connection/ConnectionTest.java, tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/wizard/deployimage/DeployImageWizardModelTest.java
=> [JBIDE-22595] dont allow pw-prompt while in connection wizard

plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/listeners/CDKOpenshiftUtility.java
There is an extra trailing space in the default docker
registry url.
=> JBIDE-22671 Remove trailing space in registry url

plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/OpenShiftCommonUIConstants.java, plugins/org.jboss.tools.openshift.express.ui/src/org/jboss/tools/openshift/express/internal/ui/wizard/application/ExpressApplicationWizard.java, plugins/org.jboss.tools.openshift.express.ui/src/org/jboss/tools/openshift/express/internal/ui/wizard/application/GitCloningSettingsWizardPageModel.java, plugins/org.jboss.tools.openshift.express.ui/src/org/jboss/tools/openshift/express/internal/ui/wizard/application/IOpenShiftApplicationWizardModel.java, plugins/org.jboss.tools.openshift.express.ui/src/org/jboss/tools/openshift/express/internal/ui/wizard/application/OpenShiftApplicationWizardModel.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/importapp/ImportApplicationWizard.java, tests/org.jboss.tools.openshift.express.test/META-INF/MANIFEST.MF, tests/org.jboss.tools.openshift.express.test/src/org/jboss/tools/openshift/express/test/ui/wizard/application/GitCloningSettingsWizardPageModelTest.java, tests/org.jboss.tools.openshift.test/META-INF/MANIFEST.MF, tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/wizard/importapp/ImportApplicationWizardModelTest.java
- Use common dialog settings to store the Git repo value
=> [JBIDE-22649] - When importing an OS2 app, the Git import does not use the default import folder used while importing OS3

plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/RSync.java
- Suppress perms mapping when performing oc rsync
=> [JBIDE-22773] - Openshift server adapter can't start with eap64-basics2i template on Windows: can't copy MANIFEST.MF reported

plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/RSync.java
eap64-basic-s2i template on Windows: cannot copy MANIFEST.MF reported (#1264)
This reverts commit 7a2c6cf9bbb0740f5867ab1a61314bef77f4c4ba.
=> Revert [JBIDE-22773] - Openshift server adapter can't start with

plugins/org.jboss.tools.openshift.client/.classpath, plugins/org.jboss.tools.openshift.client/META-INF/MANIFEST.MF, plugins/org.jboss.tools.openshift.client/pom.xml
depends on https://github.com/openshift/openshift-restclient-java/pull/202 being deployed
cc @fbricon
=> bump for openshift-restclient-java-5.0.0-RC1

plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/connection/Connection.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/models/AbstractOpenshiftUIElement.java
Shortly about the bug:
All OS connections in OS Explorer view a stored in CustomHashtable elementMap (see org.eclipse.jface.viewers.StructuredViewer class). We add connection there when the view is being opened (for example on eclipse startup). At that moment connection to the remote server is not established yet. And, say, hash1 is generated when adding to map. After we provide the token and want to expand the connection UI element, the real connection to the remote server almost always has already bee established and ANOTHER hash2 was generated. That's why connection wasn't just found in the view.
This bug is more about the way how java counts hashCode for URL objects. The thing is that it tries to resolve ip address and connect to the URL. You can find lots of posts complaining on that …
=> jbide-22471: connection stays "Loading" after the token provided

plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/OpenShiftServerEditorSection.java
After a failure to load,  variable "initializing" is still true, so changes to editor do not take effect.
=> JBIDE-22640 - after failure to init editor, editor is unusable.

plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/ImageStreamTagMetaData.java
- Change decision between Config and ContainerConfig
=> [JBIDE-22916] - Deploy Docker Wizard: Deploying a docker image from OpenShift explorer does not fetch metadata

plugins/org.jboss.tools.openshift.cdk.server/META-INF/MANIFEST.MF, plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/VagrantPoller.java, plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/controllers/CDKLaunchController.java, plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/controllers/CDKShutdownController.java, plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/controllers/VagrantLaunchUtility.java, plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/listeners/ServiceManagerEnvironment.java
Test patch to see if cdt.native works to fix the issue for windows and mac. 
This patch isn't suitable for merging and needs cleaning up. It's actually the same patch as before with just 3 or 4 lines changed, but since I've already reverted the original, the patch seems longer.
=> JBIDE-23039 - an interactive terminal solution for all three operating major OS types

plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/job/DeployImageJob.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/DeployImageWizard.java, tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/job/DeployImageJobTest.java
@jeffmaury @jcantrill @adietish , please, have a look
Possibly it is better to do update in a separate method, but then we need to get DC from connection again. Also i believe, that some better naming for the method can be created
=> jbide-22626: Updating deployed docker image on OpenShift does not work

plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/job/DeployImageJob.java
- ImageStream is created with tag to mimic oc behavior
Signed-off-by: Jeff MAURY jmaury@redhat.com
=> [JBIDE-22915] - Deploy Docker Image: Replication controller is not created for some images

tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/job/DeployImageJobTest.java
=> [JBIDE-23486] - Build: DeployImageJobtest#testStubImageStreamWhereOneDoesNotExistAndImageIsPublic is failing

plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/debug/DebugSessionTracker.java, plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/debug/DebugTrackerContributionEvaluation.java, plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/behavior/OpenShiftShutdownController.java, plugins/org.jboss.tools.openshift.js/src/org/jboss/tools/openshift/internal/js/storage/SessionStorage.java, plugins/org.jboss.tools.openshift.js/src/org/jboss/tools/openshift/js/debug/NodeDebugSessionTracker.java, plugins/org.jboss.tools.openshift.js/src/org/jboss/tools/openshift/js/launcher/NodeDebugLauncher.java
QE needs to +1 this PR
Signed-off-by: Ilya Buziuk <ibuziuk@redhat.com>
=> JBIDE-23421: Terminating Server Adapter running in debug mode does not terminate Node.js debug session

plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/OpenShiftServerUtils.java, plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/OpenshiftJMXConnectionProvider.java, plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/behavior/OpenShiftLaunchController.java, tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/core/server/OpenShiftServerUtilsTest.java
=> [JBIDE-23514] - Server adapter: adapters for non-java app should not have a JMX child (double clicking it causes error)

features/org.jboss.tools.openshift.cdk.test.feature/feature.xml, test-framework/org.jboss.tools.cdk.reddeer/.gitignore, test-framework/org.jboss.tools.cdk.reddeer/META-INF/MANIFEST.MF, test-framework/org.jboss.tools.cdk.reddeer/build.properties, test-framework/org.jboss.tools.cdk.reddeer/plugin.xml, test-framework/org.jboss.tools.cdk.reddeer/pom.xml, test-framework/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/Activator.java, test-framework/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/condition/ServerHasState.java, test-framework/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/preferences/OpenShift3SSLCertificatePreferencePage.java, test-framework/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/requirements/DisableSecureStorageRequirement.java, test-framework/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/ui/CDEServer.java, test-framework/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/ui/CDEServersView.java, test-framework/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/ui/wizard/CredentialsWizardPage.java, test-framework/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/ui/wizard/NewServerContainerWizardPage.java, test-framework/pom.xml
=> JBIDE-23770 - Move cdk.reddeer test-framework to jbosstools-openshift

test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/requirement/OpenShiftProjectRequirement.java, test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/requirement/OpenShiftServiceRequirement.java, test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/utils/v3/OpenShift3NativeProjectUtils.java, test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/utils/v3/OpenShift3NativeResourceUtils.java
So this logic can be consumed by tests.
=> (itests, test-framework) Move Project creation logic from requirement to separate class.

plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/utils/UIUtils.java, plugins/org.jboss.tools.openshift.express.ui/src/org/jboss/tools/openshift/express/internal/ui/wizard/application/ApplicationConfigurationWizardPage.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/OpenShiftServerEditorSection.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/DeployImagePage.java
corrected layout issues in OpenShiftServerEditorSection and centralized
the paintlistener, that ensures combos in GTK3 have the correct size, to
UIUtils#ensureGTK3CombosAreCorrectSize
=> [JBIDE-23783] fixed layout in server editor section

plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/OpenShiftServerUtils.java, tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/core/server/OpenShiftServerUtilsTest.java
=> [JBIDE-23821] fix NPE when existing server has no type

plugins/org.jboss.tools.openshift.client/.classpath, plugins/org.jboss.tools.openshift.client/META-INF/MANIFEST.MF, plugins/org.jboss.tools.openshift.client/pom.xml
=> [JBIDE-23862] using latest osjc so that paths to "oc" may have " "

test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/utils/SecureStorage.java, test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/utils/TestUtils.java
I've found some uses for this method outside the secure storage handler. TestUtils seems like a good place to make it public.
=> Test-framework: Move acceptSSLCertificate method to a public place

test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/utils/v3/OpenShift3NativeProjectUtils.java
The tree item lookup uses displayed name, but the method would use project name and error every time these names differ.
=> Test-framework: wait for project creation based on displayed name

plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/behavior/OpenShiftPublishController.java
I'm really not sure about the correctness of the fix, but it works for me.
The thing is that, despite the fact that the publish kind is called `IServer.PUBLISH_CLEAN` it doesn't clean all the deployed files, but just a changed one: here is rsync log from Console View after the changes in Member.java:
> sent 46 bytes  received 1,375 bytes  2,842.00 bytes/sec
total size is 8,535,536  speedup is 6,006.71
sending incremental file list
ROOT.war.dodeploy
ROOT.war/WEB-INF/classes/org/jboss/as/quickstarts/kitchensink/model/Member.class
sent 2,147 bytes  received 190 bytes  1,558.00 bytes/sec
total size is 8,535,531  speedup is 3,652.35
i'm mostly unsure about the condition `isEapProfile()`. Is it ok to check if it is a EAP project like this?
@adietish @robstryker @jeffmaury please, take a look …
=> JBIDE-23603: do a clean publish for eap

plugins/org.jboss.tools.openshift.client/.classpath, plugins/org.jboss.tools.openshift.client/META-INF/MANIFEST.MF, plugins/org.jboss.tools.openshift.client/pom.xml
=> [JBIDE-23883] using openshift-restclient-5.5.0.Final

plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/property/BuildConfigPropertySource.java
=> [JBIDE-23815] dont NPE when BuildConfig.source.type is "Binary"

test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/condition/ServerAdapterExists.java, test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/view/resources/ServerAdapter.java
Kind of resource (Service, Deployment config, ...) for which was the
server adapter created was added to name of the server adapter.
=> Fix for integration tests reflecting edited name of Server Adapter.

plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/handler/PodLogsHandler.java
=> [JBIDE-23708] - Pod Log: unable to get build log if build failed with error

plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/SelectResourceWizard.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/ServerSettingsWizardPage.java
=> [JBIDE-24033] finish adapter wizard upon double clicking resource

plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/newapp/NewApplicationWizardModel.java
=> 	JBIDE-23769 - New Application: Do not throw exception in error log when provided template is of wrong kind.

plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/models/ProjectWrapper.java
=> JBIDE-24250 - OpenShift Explorer sometimes don't show the objects in Properties view

plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/dockerutils/PushImageToRegistryJob.java
=> JBIDE-24373 - Can't push an image to the CDK3 Docker registry

plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/RSync.java
=> jbide-24322: rsync via tar strategy creates nested folders

plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/OpenShiftServerUtils.java
=> JBIDE-24241 - Server adapter not working when created from replication controller fallback

plugins/org.jboss.tools.openshift.common.core/src/org/jboss/tools/openshift/common/core/connection/HumanReadableX509Certificate.java, tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/common/core/connection/HumanReadableX509CertificateTest.java
* fix test to assert date independently of timezones
=> [JBIDE-24312] fix HumanReadableX509CertificateTest.shouldReportValidity

test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/utils/OpenShiftLabel.java, test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/utils/v3/OpenShift3NativeProjectUtils.java, test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/wizard/v3/TemplatesCreator.java
When projects get deleted it takes some time to be "really" deleted.
Tests sometimes recreate the same project and fail. This should fix
that.
=> ITests: Try creating project multiple times before failing.

test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/utils/OpenShiftLabel.java, test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/utils/v3/OpenShift3NativeProjectUtils.java
=> ITests: Extend wait for project creation & change label of builder image.

plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/newapp/ApplicationSourceListPage.java
=> JBIDE-24448 - fix validator error by making redraw async

plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/listeners/MinishiftServiceManagerEnvironmentLoader.java, plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/listeners/ServiceManagerEnvironment.java, plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/listeners/VagrantServiceManagerEnvironmentLoader.java
=> JBIDE-24783 - don't use default image registry url

plugins/org.jboss.tools.openshift.common.core/src/org/jboss/tools/openshift/internal/common/core/util/CommandLocationLookupStrategy.java
The command we were using is generating some
redundant output that we don't want.
Signed-off-by: Martin Malina <mmalina@redhat.com>
=> JBIDE-24881 Change command to get PATH on Mac

test-framework/org.jboss.tools.cdk.reddeer/META-INF/MANIFEST.MF, test-framework/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/core/condition/ServerHasState.java, test-framework/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/core/condition/SystemJobIsRunning.java, test-framework/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/core/matcher/JobMatcher.java, test-framework/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/server/exception/CDKServerException.java, test-framework/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/server/ui/CDEServer.java
- added new CDKServerException class
- moved another classes from integration test repo under cdk.reddeer plugin
=> Throwing of exception instead of test fail when server fails to start

plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/behavior/OpenShiftLaunchController.java, plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/server/debug/OpenShiftDebugMode.java, tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/core/server/debug/OpenShiftDebugModeTest.java
=> [JBIDE-24965] retrieve pod when restarting adapter in debug

test-framework/org.jboss.tools.cdk.reddeer/META-INF/MANIFEST.MF, test-framework/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/server/ui/CDEServer.java, test-framework/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/server/ui/CDEServersView.java
=> CDEServersView.getServer should override parent's getServer

plugins/org.jboss.tools.openshift.io.core/build.properties
=> Fix missing plugin.xml in org.jboss.tools.openshift.io.core

plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/behavior/OpenShiftLaunchController.java, plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/server/debug/OpenShiftDebugMode.java, plugins/org.jboss.tools.openshift.js/src/org/jboss/tools/openshift/js/server/behaviour/OpenShiftNodejsLaunchController.java
=> [JBIDE-25057] always enable devmode for all servers (was: only nodejs)

plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/detection/CDK3RuntimeDetector.java, tests/org.jboss.tools.openshift.cdk.server.test/META-INF/MANIFEST.MF, tests/org.jboss.tools.openshift.cdk.server.test/src/org/jboss/tools/openshift/cdk/server/test/AllTestsSuite.java, tests/org.jboss.tools.openshift.cdk.server.test/src/org/jboss/tools/openshift/cdk/server/test/internal/CDKRuntimeDetectorTest.java
=> JBIDE-25167 - both cdk3 runtime detectors validate against cdk3 / 3.1

itests/org.jboss.tools.cdk.ui.bot.test/pom.xml
=> Make cdk itests not to run by default

itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/connection/v3/CreateNewConnectionTest.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/connection/AdvancedConnectionEditor.java, test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/utils/OpenShiftLabel.java
=> [JBIDE-25121] - Connection wizard: Image Registry URL is not decorated when not valid (and validation seems weird)

tests/org.jboss.tools.openshift.cdk.server.test/src/org/jboss/tools/openshift/cdk/server/test/internal/CDK32LaunchControllerTest.java
=> [JBIDE-25382] - CDK32LaunchControllerTest fails on Windows

plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/controllers/CDK3LaunchController.java, tests/org.jboss.tools.openshift.cdk.server.test/META-INF/MANIFEST.MF, tests/org.jboss.tools.openshift.cdk.server.test/src/org/jboss/tools/openshift/cdk/server/test/CDKTestActivator.java, tests/org.jboss.tools.openshift.cdk.server.test/src/org/jboss/tools/openshift/cdk/server/test/internal/CDK32LaunchControllerTest.java
=> JBIDE-25308 - minishift_home is not passed to launch command

plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/connection/AdvancedConnectionEditor.java
Change of implementation of MessageBox (using built-in dialogs) dialog to MessageDialog class that comes from JFace layer and can be operated with RedDeer framework.
=> JBIDE-25396 Overwrite registry URL confirmation dialog change from MessageBox class to MessageDialog

itests/org.jboss.tools.openshift.ui.bot.test/META-INF/MANIFEST.MF, itests/org.jboss.tools.openshift.ui.bot.test/README.md, itests/org.jboss.tools.openshift.ui.bot.test/launchers/OpenShift3BotTests.launch, itests/org.jboss.tools.openshift.ui.bot.test/pom.xml, itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/OpenShift3BotTests.java, itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/integration/openshift/io/GetOpenShiftIOTokenTest.java, test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/preference/page/OpenShifIOPreferencePage.java, test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/utils/DatastoreOS3.java, test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/utils/SecureStorage.java, test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/utils/SystemProperties.java
=> JBIDE-25194 OpenShift IO Integration test

plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/detection/AbstractCDKRuntimeDetector.java
=> [JBIDE-25347] - cdk file kept open preventing delete from the command line

plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/SelectProjectComponentBuilder.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/ServerSettingsWizardPage.java
=> JBIDE-25227- increase widget spacing so control decorator is visible

plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/CDK3Server.java, plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/controllers/AbstractCDKShutdownController.java, plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/controllers/CDK3ShutdownController.java
=> JBIDE-25262 - ensure server state can be stopped if minishift-home disappears

plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/newapp/ApplicationSourceListPage.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/newapp/ResourceDetailsLabelProvider.java, tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/internal/ui/wizard/newapp/ResourceDetailsLabelProviderTest.java
it's more an enhancement
* Are method-/class-/variable-names meaningful? 
yes 
* Are methods concise, not too long? 
no
yes
yes
not needed any, i suppose
yes
hope so
yes
=> jbide-25448: template details - show the values, not names of parameters

plugins/org.jboss.tools.openshift.client/pom.xml, plugins/org.jboss.tools.openshift.express.client/pom.xml, plugins/org.jboss.tools.openshift.io.core/pom.xml, plugins/org.jboss.tools.openshift.ui/pom.xml
- Removed version of maven-dependency-plugin as its given by parent
=> [JBIDE-25514] - Build to not allow goal dependency:tree

itests/org.jboss.tools.openshift.ui.bot.test/pom.xml, itests/org.jboss.tools.openshift.ui.bot.test/resources/oclinks.properties, itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/common/OCBinaryLocationTest.java, test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/preference/page/OpenShift3PreferencePage.java, test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/requirement/OpenShiftCommandLineToolsRequirement.java, test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/utils/DatastoreOS3.java, test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/utils/OpenShiftLabel.java, test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/utils/SystemProperties.java, test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/utils/TestUtils.java
- Downloaded oc is copied from extracted folder instead of being symlinked
- OCBinary takes multiple parameters, bool: cleanup, setInPrefs, ocExists, downloadNewestOC
- String param: pathToOC
=> Rewrite OCBinary requirement to be configurable

plugins/org.jboss.tools.openshift.io.ui/plugin.xml
=> Don't show OSIO icon if Analytics plugin is installed

plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/OpenShiftCoreMessages.java, plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/OpenShiftCoreMessages.properties, plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/util/RSyncValidator.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/OpenShiftServerEditorModel.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/ServerSettingsWizardPage.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/ServerSettingsWizardPageModel.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/newapp/NewApplicationWizard.java
- Add check for rsync environment
=> [JBIDE-22773] - Openshift server adapter can't start with eap64-basic-s2i template on Windows: can't copy MANIFEST.MF reported

itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/OpenShift3StableBotTests.java, itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/adapter/ServerAdapterFromResourceTest.java, itests/org.jboss.tools.openshift.ui.bot.test/src/org/jboss/tools/openshift/ui/bot/test/application/v3/advanced/CreateResourcesTest.java
=> JBIDE-25215 ServerAdapterFromResourceTest fix

pom.xml
after trying a workaround described here https://github.com/revelc/formatter-maven-plugin/issues/260: wrap javadocs with html into @formatter:off/on, i decided to disable the plugin by now, because this workaround didn't help for some reason.
So we need to wait for `org.eclipse.jdt.core` release of version equal or above 3.14.0 in March 2018.
=> jbide-25551: disable formatter until Oxygen.3 release in March 2018

plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/resource/NewResourceWizard.java
- Display error message if exception is thrown during content retrieval
=> [JBIDE-25166] - Resource wizard: using (formally valid) URL to non-existing/erroneous json does not show error message

plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/RSync.java
=> [JBIDE-25743] - Permissions errors on Windows when rsyncing to Online OpenShift environments

plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/utils/DateTimeUtils.java, tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/common/ui/utils/DateTimeUtilsTest.java
=> jbide-25765: DateTimeParseException due to java 9 migration

plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/CDKServer.java
=> JBDS-4682 - return empty array instead of default impl null

plugins/org.jboss.tools.openshift.client/.classpath, plugins/org.jboss.tools.openshift.client/META-INF/MANIFEST.MF, plugins/org.jboss.tools.openshift.client/pom.xml, plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/RSync.java, plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/behavior/OpenShiftLaunchController.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/job/PodLogsJob.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/portforwading/PortForwardingWizardModel.java
=> [JBIDE-25506] exclude .git, .npm when rsync'ing

plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/OpenShiftServerUtils.java, plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/behavior/springboot/OpenShiftSpringBootPublishController.java
=> [JBIDE-25813] adapter: name resource that couldn't be found when failing

plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/RSync.java
=> [JBIDE-25700] dont preserve permissions when rsync'ing

plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/behavior/OpenShiftLaunchController.java, plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/behavior/OpenShiftShutdownController.java, plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/server/debug/DebugLaunchConfigs.java
=> DebugLaunchConfigs NPE on workspace shutdown

plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/detection/UnifiedMinishiftRuntimeDetector.java
=> JBIDE-25858 - bad logic prevents ms binary loc being set in dl-rt

plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/CDK3Server.java, plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/controllers/CDK3LaunchController.java, plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/ui/internal/view/CDKActionProvider.java, plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/ui/internal/view/SetupCDKJob.java
=> JBIDE-25908 - allow setup-cdk to be run more conveniently during launch

itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/CDKAllTestsSuite.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/MinishiftAllTestsSuite.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/CDK32ServerAdapterProfilesTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/CDKServerAdapterAbstractTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/MinishiftServerAdapterProfilesTest.java
=> New integration tests for CDK/minishift server adapter profiles feature

plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/adapter/controllers/CDK3LaunchController.java
=> JBIDE-25918 Setup cdk to be called only for CDK based adapters

plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/core/internal/detection/UnifiedMinishiftRuntimeDetector.java
=> JBIDE-25922 - ensure runtime detection identifies identical adapters

itests/org.jboss.tools.cdk.ui.bot.test/pom.xml
=> Extending timeouts in CDK itests pom.xml

plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/ICommonAttributes.java
=> [JBIDE-26043] - Two paths to OC client in properties view for OpenShift connection

plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/cdk/server/ui/internal/Minishift17ServerWizardFragment.java
=> JBIDE-26014 - fix ui error when downloading minishift on windows

plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/explorer/OpenShiftExplorerContentProvider.java
=> jbide-26084: Explorer: pods are shown twice if they're controlled by an

plugins/org.jboss.tools.openshift.client/.classpath, plugins/org.jboss.tools.openshift.client/META-INF/MANIFEST.MF, plugins/org.jboss.tools.openshift.client/pom.xml
=> [JBIDE-26172] latest client 6.1.1.Final fixing OpenShift 3.10

plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/validator/ProjectNameValidator.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/project/NewProjectWizardPage.java
=> [JBIDE-26153] - When creating an OpenShift project, rule must be displayed first

itests/org.jboss.tools.cdk.ui.bot.test/pom.xml, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/CDK32ServerAdapterProfilesTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/CDKServerAdapterAbstractTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/CDKServerAdapterSetupCDKTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/openshift/CDKImageRegistryUrlAbstractTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/openshift/CDKImageRegistryUrlValidatorTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/download/CDK32DownloadRuntimeTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/download/CDK3DownloadRuntimeTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/download/DownloadContainerRuntimeAbstractTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/download/DownloadContainerRuntimeDefaultSettingsTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/download/DownloadLatestContainerRuntimeTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/download/DownloadRuntimesWizardTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/download/MinishiftDownloadRuntimeTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/utils/CDKTestUtils.java, test-framework/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/core/enums/CDKVersion.java, test-framework/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/server/ui/CDKServer.java
=> CDK itests stabilization on jenkins

test-framework/org.jboss.tools.openshift.reddeer/pom.xml
org.jboss.tools.openshift.reddeer (changing version from 1.16 to 1.18)
=> Fix for org.apache.commons vulnerable dependency in

plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/common/ResourceLabelsPage.java
=> [JBIDE-26151] - When creating a resource label, rule must be displayed first

plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/handler/AbstractOpenShiftCliHandler.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/handler/PodLogsHandler.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/handler/PortForwardingHandler.java
=> [JBIDE-26380] lookup connection via resource when tailing pod log

itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/CDK32IntegrationTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/CDK32ServerAdapterProfilesTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/CDKServerAdapterAbstractTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/CDKServerAdapterSetupCDKTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/CDKWrongCredentialsTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/MinishiftServerAdapterProfilesTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/MinishiftServerAdapterTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/openshift/CDKImageRegistryUrlDiscoveryFailureTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/openshift/CDKImageRegistryUrlDiscoveryTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/openshift/CDKImageRegistryUrlValidatorTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/editor/CDK32ServerEditorTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/editor/MinishiftServerEditorTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/editor/launch/CDKLaunchConfigurationTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/CDK32ServerWizardTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/MinishiftServerWizardTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/download/DownloadRuntimesWizardTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/download/MinishiftDownloadRuntimeTest.java, test-framework/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/core/handlers/ServerOperationHandler.java, test-framework/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/requirements/ContainerRuntimeServerRequirement.java, test-framework/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/server/ui/CDKServer.java
- Patching DownloadRuntime wizard error message
- Update ContainerRuntime requirement class to have an option of passing existing cdk/minishift binary via env. property
=> Patch CDK itests to provide an option to run nightly builds of cdk

itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/CDKAllTestsSuite.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/CDKServerAdapterAbstractTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/MinishiftServerAdapterTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/editor/CDK32ServerEditorTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/editor/MinishiftServerEditorTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/runtime/CDK32RuntimeDetectionDevstudioStartUpTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/runtime/CDK32RuntimeDetectionTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/runtime/CDK3RuntimeDetectionTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/runtime/CDKRuntimeDetectionTemplate.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/download/CDK3DownloadRuntimeTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/download/DownloadContainerRuntimeDefaultSettingsTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/download/DownloadLatestContainerRuntimeTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/download/MinishiftDownloadRuntimeTest.java, test-framework/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/core/enums/CDKServerAdapterType.java, test-framework/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/core/enums/CDKVersion.java
- Add another release minishift version
- Make CDKRuntimeDetectionTest robust
=> JBIDE-26339 - Update cdk.itests to use minishift 1.24

itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/CDK32IntegrationTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/CDK32ServerAdapterProfilesTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/CDKServerAdapterAbstractTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/CDKServerAdapterSetupCDKTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/CDKWrongCredentialsTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/openshift/CDKImageRegistryUrlDiscoveryFailureTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/openshift/CDKImageRegistryUrlDiscoveryTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/openshift/CDKImageRegistryUrlValidatorTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/editor/CDK32ServerEditorTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/editor/MinishiftServerEditorTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/editor/launch/CDKLaunchConfigurationTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/runtime/CDK32RuntimeDetectionTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/download/CDK32DownloadRuntimeTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/download/DownloadContainerRuntimeDefaultSettingsTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/download/DownloadLatestContainerRuntimeTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/download/DownloadRuntimesWizardTest.java, test-framework/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/core/enums/CDKVersion.java, test-framework/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/server/ui/CDKServer.java
- upversioning of cdk/minishift artifacts
=> Adjusting cdk server start up timeouts

plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/behavior/ActivateMavenProfileJob.java, plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/behavior/OpenShiftLaunchController.java, plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/behavior/OpenShiftShutdownController.java
=> [JBIDE-26562] OSServerLauncher: dont join with maven switching job

plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/DockerImageLabels.java, plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/OpenShiftServerUtils.java, plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/PodDeploymentPathMetadata.java, plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/behavior/OpenShiftLaunchController.java, plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/behavior/OpenShiftPublishController.java, plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/server/debug/DebugContext.java, plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/util/ResourceUtils.java, plugins/org.jboss.tools.openshift.js/src/org/jboss/tools/openshift/js/launcher/NodeDebugLauncher.java, tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/core/server/DockerImageLabelsTest.java, tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/util/ResourceMocks.java
Allow docker image uri (where the docker image labels for
deployment-dir, debug-mode & debug port are present) to be extracted
from dc>spec>template>spec>containers if there's no
dc>spec>trigger>ImageChange
=> [JBDS-4777] Extract docker image uri from container spec

plugins/org.jboss.tools.openshift.core/plugin.xml, plugins/org.jboss.tools.openshift.core/schema/org.jboss.tools.openshift.core.dialogProvider.exsd, plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/IDialogProvider.java, plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/OpenShiftServerUtils.java, plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/Dialogs.java, plugins/org.jboss.tools.openshift.js/src/org/jboss/tools/openshift/js/server/behaviour/OpenShiftNodejsLaunchController.java, plugins/org.jboss.tools.openshift.ui/plugin.xml, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/dialog/DialogProvider.java
=> [JBIDE-26408] warn that debugging nodejs only supports node.js <=7

plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/OpenShiftServer.java, plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/OpenShiftServerUtils.java, plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/OutputNamesCacheFactory.java, plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/RSync.java, plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/behavior/OpenShiftPublishController.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/server/OpenShiftDeploymentPage.java, tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/core/server/OutputNamesCacheTest.java, tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/core/server/util/OpenShiftServerTestUtils.java
=> [JBIDE-26746] remove old deployment when outputName changes

plugins/org.jboss.tools.openshift.client/.classpath, plugins/org.jboss.tools.openshift.client/META-INF/MANIFEST.MF, plugins/org.jboss.tools.openshift.client/pom.xml, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/models/ConnectionWrapper.java
this depends on https://github.com/openshift/openshift-restclient-java/issues/395 being merged and the client library 8.0.1 being published to maven repo.
=> [JBIDE-26813] use openshift-restclient-java 8.0.1

plugins/org.jboss.tools.openshift.cdk.server/src/org/jboss/tools/openshift/internal/crc/server/core/adapter/CRC100Server.java
We typically don't add the (Tech Preview) to the server name itself, but rather to the server type. The server names should not have rogue (tech Preview) hanging out there forever because then when the user updates their workspace, those old servers will still be named tech preview, which is not desirable. 
This PR fixes the default naming for the server type to remove the Tech Preview and make sure both methods of creating runtimes use the same default name logic. 
* Are there integration tests (or …
=> JBIDE-26880 - fix default naming for crc servers

itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/CRCIntegrationTest.java
=> Fixing changed crc running status string to align with tests

tests/org.jboss.tools.openshift.egit.test/src/org/jboss/tools/openshift/egit/internal/test/util/TestProject.java, tests/org.jboss.tools.openshift.egit.test/src/org/jboss/tools/openshift/egit/internal/test/util/TestRepository.java
=> JBIDE-27197: Unit test are randomly failing because of EGit cleanup

itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/CDK32IntegrationTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/CDK32ServerAdapterProfilesTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/CDKServerAdapterSetupCDKTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/openshift/CDKImageRegistryUrlDiscoveryFailureTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/openshift/CDKImageRegistryUrlDiscoveryTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/openshift/CDKImageRegistryUrlValidatorTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/editor/CDK32ServerEditorTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/editor/launch/CDKLaunchConfigurationTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/runtime/CDK32RuntimeDetectionTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/runtime/CRCRuntimeDetectionTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/download/CRCDownloadRuntimeTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/download/DownloadContainerRuntimeDefaultSettingsTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/download/DownloadRuntimesWizardTest.java, test-framework/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/core/enums/CDKServerAdapterType.java, test-framework/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/core/enums/CDKVersion.java, test-framework/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/utils/CDKUtils.java
=> Fixing download runtime changed names

plugins/org.jboss.tools.openshift.ui/plugin.xml, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/handler/applicationexplorer/RefreshHandler.java
=> JBIDE-27349 Add refresh button for cluster in OpenShift Application

itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/CDK32IntegrationTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/CDK32ServerAdapterProfilesTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/CDKServerAdapterSetupCDKTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/CDKWrongCredentialsTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/CRCIntegrationTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/MinishiftServerAdapterProfilesTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/MinishiftServerAdapterTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/openshift/CDKImageRegistryUrlDiscoveryFailureTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/openshift/CDKImageRegistryUrlDiscoveryTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/adapter/openshift/CDKImageRegistryUrlValidatorTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/editor/CDK32ServerEditorTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/editor/MinishiftServerEditorTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/editor/launch/CDKLaunchConfigurationTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/runtime/CDK32RuntimeDetectionTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/runtime/CRCRuntimeDetectionTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/download/CDK32DownloadRuntimeTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/download/CRCDownloadRuntimeTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/download/DownloadContainerRuntimeDefaultSettingsTest.java, itests/org.jboss.tools.cdk.ui.bot.test/src/org/jboss/tools/cdk/ui/bot/test/server/wizard/download/MinishiftDownloadRuntimeTest.java, test-framework/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/core/enums/CDKVersion.java, test-framework/org.jboss.tools.cdk.reddeer/src/org/jboss/tools/cdk/reddeer/utils/CDKUtils.java
=> Update crc starting server workflow, update container runtimes

features/org.jboss.tools.openshift.feature/feature.xml
=> JBIDE-27796: BYOE does not install Oauth UI needed by devsandbox

plugins/org.jboss.tools.openshift.ui/META-INF/MANIFEST.MF, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/applicationexplorer/OpenShiftApplicationExplorerContentProvider.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/applicationexplorer/OpenShiftApplicationExplorerLabelProvider.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/handler/applicationexplorer/CreateComponentHandler.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/handler/applicationexplorer/NewProjectHandler.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/models/applicationexplorer/ApplicationExplorerUIModel.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/models/applicationexplorer/CreateComponentMessageElement.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/models/applicationexplorer/CreateProjectMessageElement.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/models/applicationexplorer/LoginMessageElement.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/odo/OdoCli.java, tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/applicationexplorer/OpenShiftApplicationExplorerContentProviderTest.java
- Have a cluster with no projects, you should see a node with a link under the cluster node that allows to create a new project
- Have a project without deployments, you should see a node with a link under the project node that allows you to create a component
- Have an application without deployments (hard to reproduce go to OpenShift console and create a devfile based sample), you should see a node with a link under the application node that allows you to create a component
=> JBIDE-27829: Enhance navigation inside the Application Explorer

plugins/org.jboss.tools.openshift.ui/META-INF/MANIFEST.MF, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/applicationexplorer/ComponentTypeColumLabelProvider.java, tests/org.jboss.tools.openshift.test/src/org/jboss/tools/openshift/test/ui/applicationexplorer/ComponentTypeColumLabelProviderTest.java
=> JBIDE-28197: Component are displayed using their id not name

plugins/org.jboss.tools.openshift.cdk.server/plugin.properties
=> JBIDE-28247: CDK tooling is deprecated

plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/odo/ComponentDeserializer.java
=> JBIDE-28283: Non odo components are not visible

plugins/org.jboss.tools.openshift.ui/resources/tools.json
=> JBIDE-28499: odo 2.5.1 extraction is broken on Windows and MacOS

plugins/org.jboss.tools.openshift.common.ui/src/org/jboss/tools/openshift/internal/common/ui/utils/StyledTextUtils.java
=> JBIDE-28500: StyledTextUtils causes Not properly disposed SWT resource

plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/stack/JavaRemoteStackDebugger.java, plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/models/applicationexplorer/ComponentElement.java
=> JBIDE-28823: vert.x component missing from supported debugger
